
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSkuAttr;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class SkuAttr extends BaseSkuAttr<SkuAttr> {
	
	public static final SkuAttr dao = new SkuAttr().dao();
	
}