
//package com.cn.jm._dao.balance;
//
//import java.math.BigDecimal;
//import java.util.Date;
//
//import com.cn._gen.dao.BalanceRecordDao;
//import com.cn._gen.model.AccountBalance;
//import com.cn._gen.model.BalanceRecord;
//import com.cn.jm.core.tool.JMToolString;
//import com.jfinal.aop.Inject;
//import com.jfinal.plugin.activerecord.Db;
//import com.jfinal.plugin.activerecord.Page;
//
//
///**
// * Generated by 广州小跑robot.
// */
//public class JMBalanceRecordDao extends BalanceRecordDao{
//	
//	/**
//	 *余额收入 
//	 */
//	public static final int INCOME = 1 ; 
//	
//	/**
//	 * 余额支出
//	 */
//	public static final int EXPEND = 0 ; 
//	
//	
//	/**
//	 *支付宝收入 
//	 */
//	public static final int ALI_INCOME = 2 ; 
//	
//	/**
//	 * 支付宝支出
//	 */
//	public static final int ALI_EXPEND = -2 ; 
//	
//	/**
//	 *微信收入 
//	 */
//	public static final int WECHAT_INCOME = 3 ; 
//	
//	/**
//	 * 微信支出
//	 */
//	public static final int WECHAT_EXPEND = -3 ; 
//	
//	/**
//	 * 充值
//	 */
//	public static final int RECHAREGE = 1 ;
//	
//	/**
//	 * 提币
//	 */
//	public static final int EXTRACT = 2 ;
//	
//	/**
//	 * 红包
//	 */
//	public static final int REDPAGE = 3 ;
//	
//	
//	/**
//	 * 红包退款
//	 */
//	public static final int RETURN_RED = 4 ;
//	
//	/**
//	 * 转账好友
//	 */
//	public static final int TRANSFER = 5 ;
//	
//	/**
//	 * 转账退款
//	 */
//	public static final int RETURN_TRANSFER = 6 ;
//	
//	/**
//	 * 商品支出
//	 */
//	public static final int BUY_GOODS = 7 ;
//	
//	/**
//	 * 商品订单退款（原路）
//	 */
//	public static final int RETURN_GOODS_ORDER = 8 ;
//	
//	@Inject
//	public JMBalanceDao balanceDao ;
//	
//	/**
//	 * 
//	* method statement：多币种记录
//	* createTime：2018年7月26日下午4:59:14
//	* By JaysonLee
//	* @param userId
//	* @param type
//	* @param msgType2
//	* @param coinTypeId
//	* @param message
//	* @param amount
//	**
//	 */
//	public void saveCoin(int userId, int type, int msgType2,int coinTypeId,String message, 
//			BigDecimal amount,String coinCode,int ids,int sourceId){
//		BalanceRecord accountRecord = new BalanceRecord();
//		accountRecord.setUserId(userId);
//		accountRecord.setType(type);
//		accountRecord.setMsgType(msgType2);
//		accountRecord.setCoinTypeId(coinTypeId);
//		accountRecord.setMessage(message);
//		accountRecord.setAmount(amount);
//		accountRecord.setCoinCode(coinCode);
//		accountRecord.setIds(ids);
//		accountRecord.setSourceId(sourceId);//来源id
//		AccountBalance coinBalance = balanceDao.getByUserId(userId);
//		accountRecord.setBalance(coinBalance.getCount());
//		accountRecord.setCreateTime(new Date());
//		accountRecord.save();
////		if(msgType2 == RETURN_RED) {//红包退还
////			sendSysRedRufundMsg(accountRecord);//发送红包消息
////		}
//	}
//
//	/**
//	 * 
//	 * @date 2019年2月28日 下午6:02:16
//	 * @author JaysonLee
//	 * @Description: 查询个人账目明细
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param msgType
//	 * @param pageSize
//	 * @param pageNumber
//	 * @param month
//	 * @return
//	 *
//	 */
//	public Page<BalanceRecord> pageForApi(int userId,int msgType,int pageSize,int pageNumber,String month){
//		StringBuffer sql = new StringBuffer("from tb_balance_record where userId = ? ");
//		if(msgType != -1){
//			//-1全部1分佣2充值提现3退款
//			//1充值 2提币 3红包 4红包退款 5转账好友 6转账退款8商品原路退款9佣金
//			String msgTypes = "";
//			if(msgType == 1){
//				msgTypes = "9";
//			}else if(msgType == 2){
//				msgTypes = "1,2";
//			}else if(msgType == 3){
//				msgTypes = "8";
//			}else {
//				msgTypes = "0";
//			}
//			sql.append(" and msgType in ("+msgTypes+")");
//		}
//		if(JMToolString.isNotEmpty(month)){
//			sql.append(" and DATE_FORMAT(createTime,'%Y-%m') = '"+month+"'");
//		}
//		Page<BalanceRecord> page = BalanceRecord.dao.paginate(pageNumber, pageSize, "select * ", sql.toString(),userId);
//		return page ;
//	}
//	
//	/**
//	 * 
//	 * @date 2019年3月2日 下午5:37:57
//	 * @author JaysonLee
//	 * @Description: 统计
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param msgType
//	 * @param pageSize
//	 * @param pageNumber
//	 * @param month
//	 * @param type 0支出 1收入
//	 * @return
//	 *
//	 */
//	public BigDecimal sumRecord(int userId,int msgType,int pageSize,int pageNumber,String month,int type){
//		StringBuffer sql = new StringBuffer("select round(sum(amount),2) from tb_balance_record where userId = ? ");
//		if(msgType != -1){
//			//-1全部1红包2充值提现3转账
//			//1充值 2提币 3红包 4红包退款 5转账好友 6转账退款
//			String msgTypes = "";
//			if(msgType == 1){
//				msgTypes = "3,4";
//			}else if(msgType == 2){
//				msgTypes = "1,2";
//			}else if(msgType == 3){
//				msgTypes = "5,6";
//			}
//			sql.append(" and msgType in ("+msgTypes+")");
//		}
//		if(JMToolString.isNotEmpty(month)){
//			sql.append(" and DATE_FORMAT(createTime,'%Y-%m') = '"+month+"'");
//		}
//		sql.append(" and type = "+type);
//		BigDecimal result = Db.queryBigDecimal(sql.toString(),userId);
//		return result != null ? result : BigDecimal.ZERO;
//	}
//	
//	
//	public BalanceRecord getByUserId(int userId){
//		BalanceRecord balanceRecord = getById(userId, false);
//		return balanceRecord ;
//	}
//	
////	/**
////	 * 
////	 * @date 2019年5月13日 下午5:24:26
////	 * @author JaysonLee
////	 * @Description: 发送退款红包消息
////	 * @reqMethod post
////	 * @paramter
////	 * @pDescription	
////	 * @param balanceRecord
////	 *
////	 */
////	public void sendSysRedRufundMsg(BalanceRecord balanceRecord){
////		String getUserId [] = {balanceRecord.getUserId() +""};
////		String times = balanceRecord.getCreateTime().toString();
////		times = times.substring(0,times.length() - 2);
////		String message = "红包退还通知\n"
////				+ "退款方式：退回零钱\n"
////				+ "交易金额："+balanceRecord.getAmount()+"\n"
////				+ "退款原因："+balanceRecord.getMessage()+"\n"
////				+ "到账时间："+times+"\n";
////		
////		try {
////			new RyService().sendSysMessage(PropKit.getInt("sendSysRedRefundId"),getUserId, message);
////		} catch (Exception e) {
////			e.printStackTrace();
////		}
////	}
//}
