
package com.cn._gen.model;

import com.cn._gen.model.base.BaseNotice;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	
	public static final Notice dao = new Notice().dao();
	
}