
package com.cn._gen.model;

import com.cn._gen.model.base.BaseContent;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
	
	public static final Content dao = new Content().dao();
	
}