
package com.cn._gen.model;

import com.cn._gen.model.base.BaseLabelRelations;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class LabelRelations extends BaseLabelRelations<LabelRelations> {
	
	public static final LabelRelations dao = new LabelRelations().dao();
	
}