
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastRoomMerchant;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastRoomMerchant extends BaseWebcastRoomMerchant<WebcastRoomMerchant> {
	
	public static final WebcastRoomMerchant dao = new WebcastRoomMerchant().dao();
	
}