
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSearchHistory;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class SearchHistory extends BaseSearchHistory<SearchHistory> {
	
	public static final SearchHistory dao = new SearchHistory().dao();
	
}