
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAccountUser;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class AccountUser extends BaseAccountUser<AccountUser> {
	
	public static final AccountUser dao = new AccountUser().dao();
	
}