
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAccountSession;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class AccountSession extends BaseAccountSession<AccountSession> {
	
	public static final AccountSession dao = new AccountSession().dao();
	
}