
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAddress;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Address extends BaseAddress<Address> {
	
	public static final Address dao = new Address().dao();
	
}