
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAppVersion;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class AppVersion extends BaseAppVersion<AppVersion> {
	
	public static final AppVersion dao = new AppVersion().dao();
	
}