
package com.cn._gen.model;

import com.cn._gen.model.base.BaseBalanceRecord;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class BalanceRecord extends BaseBalanceRecord<BalanceRecord> {
	
	public static final BalanceRecord dao = new BalanceRecord().dao();
	
}