
package com.cn._gen.model;

import com.cn._gen.model.base.BaseBank;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Bank extends BaseBank<Bank> {
	
	public static final Bank dao = new Bank().dao();
	
}