
package com.cn._gen.model;

import com.cn._gen.model.base.BaseBankAccount;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class BankAccount extends BaseBankAccount<BankAccount> {
	
	public static final BankAccount dao = new BankAccount().dao();
	
}