
package com.cn._gen.model;

import com.cn._gen.model.base.BaseFreight;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Freight extends BaseFreight<Freight> {
	
	public static final Freight dao = new Freight().dao();
	
}