
package com.cn._gen.model;

import com.cn._gen.model.base.BaseFreightArea;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class FreightArea extends BaseFreightArea<FreightArea> {
	
	public static final FreightArea dao = new FreightArea().dao();
	
}