
package com.cn._gen.model;

import com.cn._gen.model.base.BaseGiftGive;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class GiftGive extends BaseGiftGive<GiftGive> {
	
	public static final GiftGive dao = new GiftGive().dao();
	
}