
package com.cn._gen.model;

import com.cn._gen.model.base.BaseGoods;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	
	public static final Goods dao = new Goods().dao();
	
}