
package com.cn._gen.model;

import com.cn._gen.model.base.BaseGoodsResale;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class GoodsResale extends BaseGoodsResale<GoodsResale> {
	
	public static final GoodsResale dao = new GoodsResale().dao();
	
}