
package com.cn._gen.model;

import com.cn._gen.model.base.BaseGoodsCart;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class GoodsCart extends BaseGoodsCart<GoodsCart> {
	
	public static final GoodsCart dao = new GoodsCart().dao();
	
}