
package com.cn._gen.model;

import com.cn._gen.model.base.BaseImg;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Img extends BaseImg<Img> {
	
	public static final Img dao = new Img().dao();
	
}