
package com.cn._gen.model;

import com.cn._gen.model.base.BaseLabelRelation;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class LabelRelation extends BaseLabelRelation<LabelRelation> {
	
	public static final LabelRelation dao = new LabelRelation().dao();
	
}