
package com.cn._gen.model;

import com.cn._gen.model.base.BaseLabel;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Label extends BaseLabel<Label> {
	
	public static final Label dao = new Label().dao();
	
}