
package com.cn._gen.model;

import com.cn._gen.model.base.BaseNo;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class No extends BaseNo<No> {
	
	public static final No dao = new No().dao();
	
}