
package com.cn._gen.model;

import com.cn._gen.model.base.BaseOptions;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Options extends BaseOptions<Options> {
	
	public static final Options dao = new Options().dao();
	
}