
package com.cn._gen.model;

import com.cn._gen.model.base.BasePayments;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Payments extends BasePayments<Payments> {
	
	public static final Payments dao = new Payments().dao();
	
}