
package com.cn._gen.model;

import com.cn._gen.model.base.BasePower;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Power extends BasePower<Power> {
	
	public static final Power dao = new Power().dao();
	
}