
package com.cn._gen.model;

import com.cn._gen.model.base.BaseProblem;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Problem extends BaseProblem<Problem> {
	
	public static final Problem dao = new Problem().dao();
	
}