
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRecharge;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Recharge extends BaseRecharge<Recharge> {
	
	public static final Recharge dao = new Recharge().dao();
	
}