
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRechargeOrder;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RechargeOrder extends BaseRechargeOrder<RechargeOrder> {
	
	public static final RechargeOrder dao = new RechargeOrder().dao();
	
}