
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRefundGoods;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RefundGoods extends BaseRefundGoods<RefundGoods> {
	
	public static final RefundGoods dao = new RefundGoods().dao();
	
}