
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRolePower;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RolePower extends BaseRolePower<RolePower> {
	
	public static final RolePower dao = new RolePower().dao();
	
}