
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRole;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	
	public static final Role dao = new Role().dao();
	
}