
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRoomRecord;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RoomRecord extends BaseRoomRecord<RoomRecord> {
	
	public static final RoomRecord dao = new RoomRecord().dao();
	
}