
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSku;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Sku extends BaseSku<Sku> {
	
	public static final Sku dao = new Sku().dao();
	
}