
package com.cn._gen.model;

import com.cn._gen.model.base.BaseUserCollect;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class UserCollect extends BaseUserCollect<UserCollect> {
	
	public static final UserCollect dao = new UserCollect().dao();
	
}