
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastRoomRecord;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastRoomRecord extends BaseWebcastRoomRecord<WebcastRoomRecord> {
	
	public static final WebcastRoomRecord dao = new WebcastRoomRecord().dao();
	
}