
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastRoom;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastRoom extends BaseWebcastRoom<WebcastRoom> {
	
	public static final WebcastRoom dao = new WebcastRoom().dao();
	
}