
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastRoomManagement;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastRoomManagement extends BaseWebcastRoomManagement<WebcastRoomManagement> {
	
	public static final WebcastRoomManagement dao = new WebcastRoomManagement().dao();
	
}