
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastRoomAccount;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastRoomAccount extends BaseWebcastRoomAccount<WebcastRoomAccount> {
	
	public static final WebcastRoomAccount dao = new WebcastRoomAccount().dao();
	
}