
package com.cn._gen.model;

import com.cn._gen.model.base.BaseWebcastBroadcastRequest;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class WebcastBroadcastRequest extends BaseWebcastBroadcastRequest<WebcastBroadcastRequest> {
	
	public static final WebcastBroadcastRequest dao = new WebcastBroadcastRequest().dao();
	
}