
package com.cn._gen.model;

import com.cn._gen.model.base.BaseZan;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Zan extends BaseZan<Zan> {
	
	public static final Zan dao = new Zan().dao();
	
}