
package com.cn.jm._dao.address;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

import com.cn._gen.dao.AddressDao;
import com.cn._gen.model.Address;
import com.cn.jm.core.db.JMToolSql;
import com.cn.jm.core.utils.util.JMResult;


/**
 * Generated by 广州小跑robot.
 */
public class JMAddressDao extends AddressDao{
	
	public JMResult add(Address address,int userId){
		int isChoice = address.getIsChoice();
		if(isChoice == 1){//默认地址
			Address defaultAddress = getDefault(userId);
			if(defaultAddress != null){
				defaultAddress.setIsChoice(0);//原来默认的不默认了
				update(defaultAddress);
			}
		}
		address.setUserId(userId);
		address.setCreateTime(new Date());
		save(address);
		return JMResult.create().code(JMResult.SUCCESS).desc("新建地址成功");
	}
	
	public JMResult edit(Address address,int userId){
		Address mAddress = getById(address.getId());
		if(!mAddress.getUserId().equals(userId)){
			return JMResult.create().code(JMResult.FAIL).desc("非法修改");
		}
		int isChoice = address.getIsChoice();
		if(isChoice == 1){//默认地址
			Address defaultAddress = getDefault(userId);
			if(defaultAddress != null){
				defaultAddress.setIsChoice(0);//原来默认的不默认了
				update(defaultAddress);
			}
		}
		address.setUserId(userId);
		address.setCreateTime(new Date());
		update(address);
		return JMResult.create().code(JMResult.SUCCESS).desc("修改地址成功");
	}

	public Address getDefault(int userId){
		return JMToolSql.get(cacheName,new Address(),"select * from shop_address where userId = ? and isChoice = 1",userId);
	}
	
	public List<Address> listByUser(int userId){
		return JMToolSql.list(cacheName,new Address(), "select * from shop_address where userId = ? order by isChoice = 1 desc,id desc ", userId);
	}
	
	public JMResult del(int userId,int id){
		HashMap<String,Object> param = new HashMap<>();
		param.put("userId", userId);
		param.put("id", id);
		Address address = get(param, false);
		if(address != null){
			delete(address);
			return JMResult.create().code(JMResult.SUCCESS).desc("删除地址成功");
		}
		return JMResult.create().code(JMResult.FAIL).desc("删除地址失败");
	}
}
