
package com.cn._gen.model;

import com.cn._gen.model.base.BaseNoticeAccount;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class NoticeAccount extends BaseNoticeAccount<NoticeAccount> {
	
	public static final NoticeAccount dao = new NoticeAccount().dao();
	
}