//
//package com.cn.jm._dao.balance;
//
//import java.math.BigDecimal;
//import java.sql.SQLException;
//import java.util.Date;
//import java.util.HashMap;
//
//import com.cn._gen.dao.AccountBalanceDao;
//import com.cn._gen.model.AccountBalance;
//import com.cn._gen.model.RechargeOrder;
//import com.cn.jm._dao.account.JMAccountDao;
//import com.cn.jm._dao.extract.JMExtractLogDao;
//import com.cn.jm._dao.recharge.JMRechargeOrderDao;
//import com.cn.jm.core.utils.util.JMResult;
//import com.jfinal.aop.Inject;
//import com.jfinal.plugin.activerecord.Db;
//import com.jfinal.plugin.activerecord.IAtom;
//
//
///**
// * Generated by 广州小跑robot.
// */
//public class JMBalanceDao extends AccountBalanceDao{
//	
//	@Inject
//	public JMBalanceRecordDao balanceRecordDao ;
//	@Inject
//	public JMRechargeOrderDao rechargeOrderDao ;
////	@Inject
////	public JMAccountExpandDao accountExpandDao ;
//	@Inject
//	public JMAccountDao accountDao ;
//	@Inject
//	public JMExtractLogDao extractLogDao ;
//	
//	public static String RMB = "RMB";
//	
//	public static int RMBId = 1;
//	
//	private static final String codeCacheName = "api_mobile_code";//验证码
//	
//	
//	/**
//	 * 
//	 * @date 2019年2月28日 下午2:52:47
//	 * @author JaysonLee
//	 * @Description: 获取某个人的余额
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @return
//	 *
//	 */
//	public AccountBalance getByUserId(int userId){
//		HashMap<String, Object> param = new HashMap<>();
//		param.put("userId",userId);
//		AccountBalance balance = get(param, false); 
//		if(balance == null){
//			add(userId, 1);
//			balance = get(param,false);
//		}
//		balance.remove("coinTypeId","coinName","coinCode","img","payCode","lastCount","display");
//		return balance ;
//	}
//	
//	public boolean add(int userId,int coinTypeId){
//		AccountBalance balance = new AccountBalance();
//		balance.setUserId(userId);
//		balance.setCoinTypeId(coinTypeId);
//		balance.setCreateTime(new Date());
//		return save(balance);
//	}
//	
//	
//	/**
//	 * 
//	 * @date 2019年2月28日 下午3:09:23
//	 * @author JaysonLee
//	 * @Description: 增加余额
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param addCount
//	 * @return
//	 *
//	 */
//	public boolean income(int userId,BigDecimal addCount){
//		HashMap<String, Object> param = new HashMap<>();
//		param.put("fz",0);
//		param.put("userId", userId);
//		AccountBalance balance = getByUserId(userId);
//		if(balance == null){
//			return false ;
//		}
//		try {
//			return Db.tx(new IAtom() {
//				@Override
//				public boolean run() throws SQLException {
//					int version = balance.getVersion();
//					int result = Db.update("update tb_account_balance set count = count + ?,version = version + 1 where version = ? and userId = ? and fz = 0 and coinTypeId = 1", addCount, version, userId);
//					return result == 1;
//				}
//			});
//		} catch (Exception e) {
//			e.printStackTrace();
//			return false ;
//		}
//	}
//	
//	/**
//	 * 
//	 * @date 2019年3月1日 上午11:48:57
//	 * @author JaysonLee
//	 * @Description: 系统充值
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param addCount
//	 * @return
//	 *
//	 */
//	public JMResult sysRecharge(int userId,BigDecimal addCount){
//		int rechargeOrderId = rechargeOrderDao.create(userId,addCount);
//		if(income(userId, addCount)){
//			balanceRecordDao.saveCoin(userId, JMBalanceRecordDao.INCOME, 
//					JMBalanceRecordDao.RECHAREGE, 1, "系统充值到账", addCount, "RMB", -1, rechargeOrderId);
//			RechargeOrder rechargeOrder = rechargeOrderDao.getById(rechargeOrderId,false);
//			rechargeOrder.setStatus(1);
//			rechargeOrderDao.update(rechargeOrder);
//			return JMResult.create().code(JMResult.SUCCESS).desc("充值成功");
//		}else{
//			return JMResult.create().code(JMResult.FAIL).desc("充值失败");
//		}
//	}
//	
//	/**
//	 * 
//	 * @date 2019年3月6日 下午3:37:43
//	 * @author JaysonLee
//	 * @Description: 系统提现
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param subCount
//	 * @return
//	 *
//	 */
////	public JMResult sysExtract(int userId,BigDecimal subCount){
////		int extractId = extractLogDao.create(userId, subCount);
////		if(consume(userId, subCount)){
////			balanceRecordDao.saveCoin(userId, JMBalanceRecordDao.EXPEND, 
////					JMBalanceRecordDao.EXTRACT, 1, "系统提现扣款", subCount, "RMB", -1, extractId);
////			ExtractLog extractLog = extractLogDao.getById(extractId,false);
////			extractLog.setState(1);//审核通过
////			extractLogDao.update(extractLog);
////			return JMResult.create().code(JMResult.SUCCESS).desc("提现成功");
////		}else{
////			return JMResult.create().code(JMResult.FAIL).desc("提现失败");
////		}
////	}
//	
//	/**
//	 * 
//	 * @date 2019年2月28日 下午4:03:46
//	 * @author JaysonLee
//	 * @Description: 消费余额
//	 * @reqMethod post
//	 * @paramter
//	 * @pDescription	
//	 * @param userId
//	 * @param subCount
//	 * @return
//	 *
//	 */
//	public boolean consume(int userId,BigDecimal subCount){
//		HashMap<String, Object> param = new HashMap<>();
//		param.put("fz",0);
//		param.put("userId",userId);
//		AccountBalance balance = getByUserId(userId);
//		if(balance == null){
//			return false ;
//		}
//		try {
//			return Db.tx(new IAtom() {
//				@Override
//				public boolean run() throws SQLException {
//					int version = balance.getVersion();
//					int result = Db.update("update tb_account_balance set count = count - ?,version = version + 1 where count >= ? and version = ? and userId = ? and fz = 0 and coinTypeId = 1",subCount,subCount,version,userId);
//					return result == 1;
//				}
//			});
//		} catch (Exception e) {
//			return false ;
//		}
//	}
//	
////	/**
////	 * 
////	 * @date 2019年3月2日 下午4:53:53
////	 * @author JaysonLee
////	 * @Description: 修改支付密码
////	 * @reqMethod post
////	 * @paramter
////	 * @pDescription	
////	 * @param password
////	 * @param code
////	 * @param userId
////	 * @return
////	 *
////	 */
////	public JMResult updatePayPwd(String password,int code,int userId){
////		if(password.length() != 6){
////			return JMResult.create().code(JMResult.FAIL).desc("请输入六位数的支付密码");
////		}
////		AccountExpand userExtend = accountExpandDao.getByAccountId(userId);
////		Account account = accountDao.getById(userId,false);
////		if(userExtend == null || account == null){
////			return JMResult.create().code(JMResult.FAIL).desc("非法操作");
////		}
////		SmsCode smsCode = JMCacheKit.get(codeCacheName+"_3",account.getMobile());
////		if (smsCode == null) {
////			return JMResult.create().code(JMResult.FAIL).desc("手机号码不正确，请重新发送验证码");
////		}
////		
////		if(smsCode.getCode() != code ){
////			return JMResult.create().code(JMResult.FAIL).desc("验证码不正确");
////		}
////		String md5Pwd = accountExpandDao.getPayPwd(password);
////		userExtend.setPayPwd(md5Pwd);
////		if(accountExpandDao.update(userExtend)){
////			JMCacheKit.remove(codeCacheName+"_3",account.getMobile());
////			return JMResult.create().code(JMResult.SUCCESS).desc("修改支付密码成功");
////		}else{
////			return JMResult.create().code(JMResult.FAIL).desc("修改支付密码失败");
////		}
////	
////	}
//	
//}
