
package com.cn._gen.model;

import com.cn._gen.model.base.BaseExtractLog;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class ExtractLog extends BaseExtractLog<ExtractLog> {
	
	public static final ExtractLog dao = new ExtractLog().dao();
	
}