
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseSkuAttr<M extends BaseSkuAttr<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
	}

	public java.lang.Integer getSkuId() {
		return get("skuId");
	}

	public void setAttrId(java.lang.Integer attrId) {
		set("attrId", attrId);
	}

	public java.lang.Integer getAttrId() {
		return get("attrId");
	}



}