
package com.cn.jm._dao.extract;

import java.math.BigDecimal;
import java.util.Date;

import com.cn._gen.dao.ExtractLogDao;
import com.cn._gen.model.ExtractLog;
import com.cn.jm.core.utils.util.NoUtils;


/**
 * Generated by 广州小跑robot.
 */
public class JMExtractLogDao extends ExtractLogDao{
	
	public int create(int userId,BigDecimal count){
		ExtractLog extractLog = new ExtractLog();
		extractLog.setNo(NoUtils.createOutTradeNo("EXT"));
		extractLog.setUserId(userId);
		extractLog.setReason("系统提现");
		extractLog.setAmount(count);
		extractLog.setCreateTime(new Date());
		save(extractLog);
		return extractLog != null ?extractLog.getId() : -1;
	}
	

}
