
package com.cn.jm._dao.spec;

import java.util.List;

import com.cn._gen.dao.SpecAttributeDao;
import com.cn._gen.model.SpecAttribute;
import com.cn.jm.core.db.JMToolSql;
import com.jfinal.plugin.activerecord.Db;


/**
 * Generated by 广州小跑robot.
 */
public class JMSpecAttributeDao extends SpecAttributeDao{
	
	public List<SpecAttribute> listspecByGoodsAndSpecId(int goodsId,int specId){
		return JMToolSql.list(cacheName, new SpecAttribute(),"select id,name from shop_spec_attribute where id in (select specAttrId from shop_spec_group where goodsId = ? and specId = ? group by specAttrId)", goodsId,specId);
	}
	
	public List<SpecAttribute> listAttrsBySpecId(int specId){
		return SpecAttribute.dao.find("select name,id from shop_spec_attribute where specId = ?",specId);
	}
	
	public List<SpecAttribute> listAttrsBySpecIdAndAttrs(int specId,String attrs){
		return SpecAttribute.dao.find("select name,id from shop_spec_attribute where specId = ? and id in ("+attrs+")",specId);
	}
	
	public String getAttrsBySpec(int specId){
		List<SpecAttribute> list = SpecAttribute.dao.find("select name,id from shop_spec_attribute where specId = ?",specId);
		String result = "";
		for(SpecAttribute attribute : list){
			result+=attribute.getName()+",";
		}
		if(result.endsWith(",")){
			result = result.substring(0,result.length()-1);
		}
		return result ;
	}
	
	/**
	 * 
	 * @date 2019年1月29日 下午6:21:59
	 * @author JaysonLee
	 * @Description: 即将被删除的
	 * @reqMethod post
	 * @paramter
	 * @pDescription	
	 * @param specId
	 * @param ids
	 * @return
	 *
	 */
	public List<SpecAttribute> listOld(int specId,String ids){
		return SpecAttribute.dao.find("select * from shop_spec_attribute where specId = ? and id not in ("+ids+")",specId);
	} 
	
}
