
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsStar<M extends BaseGoodsStar<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStarNum(java.lang.Integer starNum) {
		set("starNum", starNum);
	}

	public java.lang.Integer getStarNum() {
		return get("starNum");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setOrderGoodsId(java.lang.Integer orderGoodsId) {
		set("orderGoodsId", orderGoodsId);
	}

	public java.lang.Integer getOrderGoodsId() {
		return get("orderGoodsId");
	}

	public void setSkuCode(java.lang.String skuCode) {
		set("skuCode", skuCode);
	}

	public java.lang.String getSkuCode() {
		return get("skuCode");
	}

	public void setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
	}

	public java.lang.Integer getSkuId() {
		return get("skuId");
	}

	public void setSkuImg(java.lang.String skuImg) {
		set("skuImg", skuImg);
	}

	public java.lang.String getSkuImg() {
		return get("skuImg");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goodsName");
	}

	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goodsNum", goodsNum);
	}

	public java.lang.Integer getGoodsNum() {
		return get("goodsNum");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setImg1(java.lang.String img1) {
		set("img1", img1);
	}

	public java.lang.String getImg1() {
		return get("img1");
	}

	public void setImg2(java.lang.String img2) {
		set("img2", img2);
	}

	public java.lang.String getImg2() {
		return get("img2");
	}

	public void setImg3(java.lang.String img3) {
		set("img3", img3);
	}

	public java.lang.String getImg3() {
		return get("img3");
	}

	public void setImg4(java.lang.String img4) {
		set("img4", img4);
	}

	public java.lang.String getImg4() {
		return get("img4");
	}

	public void setImg5(java.lang.String img5) {
		set("img5", img5);
	}

	public java.lang.String getImg5() {
		return get("img5");
	}

	public void setImg6(java.lang.String img6) {
		set("img6", img6);
	}

	public java.lang.String getImg6() {
		return get("img6");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setSellerAccountId(java.lang.Integer sellerAccountId) {
		set("sellerAccountId", sellerAccountId);
	}

	public java.lang.Integer getSellerAccountId() {
		return get("sellerAccountId");
	}



}