
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAssociateRequest;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class AssociateRequest extends BaseAssociateRequest<AssociateRequest> {
	
	public static final AssociateRequest dao = new AssociateRequest().dao();
	
}