
package com.cn._gen.model;

import com.cn._gen.model.base.BaseFollow;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	
	public static final Follow dao = new Follow().dao();
	
}