
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSpecGroup;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class SpecGroup extends BaseSpecGroup<SpecGroup> {
	
	public static final SpecGroup dao = new SpecGroup().dao();
	
}