
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSpecAttribute;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class SpecAttribute extends BaseSpecAttribute<SpecAttribute> {
	
	public static final SpecAttribute dao = new SpecAttribute().dao();
	
}