
package com.cn._gen.model;

import com.cn._gen.model.base.BaseGoodsModels;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class GoodsModels extends BaseGoodsModels<GoodsModels> {
	
	public static final GoodsModels dao = new GoodsModels().dao();
	
}