
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseGiftGive<M extends BaseGiftGive<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setToAccountId(java.lang.Integer toAccountId) {
		set("toAccountId", toAccountId);
	}

	public java.lang.Integer getToAccountId() {
		return get("toAccountId");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setOrderName(java.lang.String orderName) {
		set("orderName", orderName);
	}

	public java.lang.String getOrderName() {
		return get("orderName");
	}

	public void setGiftId(java.lang.Integer giftId) {
		set("giftId", giftId);
	}

	public java.lang.Integer getGiftId() {
		return get("giftId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setMoney(java.lang.Double money) {
		set("money", money);
	}

	public java.lang.Double getMoney() {
		return get("money");
	}

	public void setIntegral(java.lang.Double integral) {
		set("integral", integral);
	}

	public java.lang.Double getIntegral() {
		return get("integral");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}