
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseLabelRelations<M extends BaseLabelRelations<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLabelId(java.lang.Long labelId) {
		set("labelId", labelId);
	}

	public java.lang.Long getLabelId() {
		return get("labelId");
	}

	public void setIds(java.lang.Long ids) {
		set("ids", ids);
	}

	public java.lang.Long getIds() {
		return get("ids");
	}



}