
package com.cn._gen.model;

import com.cn._gen.model.base.BaseOrderGoods;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class OrderGoods extends BaseOrderGoods<OrderGoods> {
	
	public static final OrderGoods dao = new OrderGoods().dao();
	
}