
package com.cn._gen.model;

import com.cn._gen.model.base.BaseAccount;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	
	public static final Account dao = new Account().dao();
	
}