
package com.cn.jm._dao.sku;

import java.util.ArrayList;
import java.util.List;

import com.cn._gen.dao.SkuAttrDao;
import com.cn._gen.model.SkuAttr;


/**
 * Generated by 广州小跑robot.
 */
public class JMSkuAttrDao extends SkuAttrDao{
	
	public List<Integer> listByGoodsId(int goodsId){
		List<SkuAttr> list = SkuAttr.dao.find("select a.attrId from shop_sku_attr a where skuId in (select id from shop_sku where goodsId = ?)",goodsId);
		List<Integer> list2 = new ArrayList<Integer>();
		for(SkuAttr skuAttr : list){
			list2.add(skuAttr.getAttrId());
		}
		return list2 ;
	}
			

}
