
package com.cn.jm._dao.extract;

import com.cn._gen.dao.ExtractLogDao;
import com.cn._gen.model.ExtractLog;
import com.cn.jm.util.SqlUtil;
import com.jfinal.kit.HashKit;
import com.jfinal.plugin.activerecord.Page;


/**
 * Generated by 广州小跑robot.
 */
public class JMExtractLogDao extends ExtractLogDao{
	
	public Page<ExtractLog> page(Integer pageNumber, Integer pageSize, String mobile, String nick, Integer state,
			String startTime, String endTime, boolean isCache){
		StringBuilder selectSql = new StringBuilder("SELECT el.*,au.mobile,au.nick ");
		StringBuilder fromSql = new StringBuilder(" FROM ");
		fromSql.append(tableName + " el");
		fromSql.append(" INNER JOIN tb_account_user au ON el.accountId = au.accountId");
		fromSql.append(" :WHERE ");
		SqlUtil.addLike(fromSql, " AND au.mobile", "%", mobile, "%");
		SqlUtil.addLike(fromSql, " AND au.nick", "%", nick, "%");
		SqlUtil.addWhere(fromSql, " AND el.state = ", state, -1);
		SqlUtil.addBetweenTime(fromSql, startTime, endTime, " AND createTime");
		fromSql.append(" ORDER BY id DESC");
		SqlUtil.changeWhere(fromSql);
		String strFromSql = SqlUtil.getSql(fromSql);
		String strSelectSql = selectSql.toString();
		return isCache?dao.paginateByCache(cacheName,HashKit.md5(selectSql.append(strFromSql).toString()), pageNumber, pageSize,false,strSelectSql, strFromSql)
			:dao.paginate(pageNumber, pageSize, false, strSelectSql,strFromSql);
	}
	
}
