
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseFreight<M extends BaseFreight<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTemplateId(java.lang.Integer templateId) {
		set("templateId", templateId);
	}

	public java.lang.Integer getTemplateId() {
		return get("templateId");
	}

	public void setFirstNum(java.lang.Double firstNum) {
		set("firstNum", firstNum);
	}

	public java.lang.Double getFirstNum() {
		return get("firstNum");
	}

	public void setFirstPrice(java.math.BigDecimal firstPrice) {
		set("firstPrice", firstPrice);
	}

	public java.math.BigDecimal getFirstPrice() {
		return get("firstPrice");
	}

	public void setSecondNum(java.lang.Double secondNum) {
		set("secondNum", secondNum);
	}

	public java.lang.Double getSecondNum() {
		return get("secondNum");
	}

	public void setSecondPrice(java.math.BigDecimal secondPrice) {
		set("secondPrice", secondPrice);
	}

	public java.math.BigDecimal getSecondPrice() {
		return get("secondPrice");
	}

	public void setSufficientPrice(java.math.BigDecimal sufficientPrice) {
		set("sufficientPrice", sufficientPrice);
	}

	public java.math.BigDecimal getSufficientPrice() {
		return get("sufficientPrice");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}



}