
package com.cn.jm.service;

import com.cn._gen.model.No;
import com.cn.jm._dao.no.JMNoDao;
import com.jfinal.aop.Aop;
/**
 * Generated by 小跑科技robot  .
 */
public class JMNoService extends BasicsService<No> {
	
	JMNoDao noDao = Aop.get(JMNoDao.class);
	
	public String getNo() {
		String strNo;
		synchronized (this) {
			No no = noDao.selectOne();
			strNo = no.getNo();
			delete(no);
		}
		return strNo;
	}

    /**
     * 获取编号总数
     * @return 
     */
    public Long selectNoCount() {
        return noDao.selectNumberByMethod("COUNT");
    }
    /**
     * 获取当前最大的值或者最小值,由于no值的最大或者最小会被获取,造成no重复,但是id不会,所以采用id
     * @return
     */
    public Long selectNoMaxNumber() {
        return noDao.selectNumberByMethod("MAX");
    }
 
    public Long selectNoMinNumber() {
        return noDao.selectNumberByMethod("MIN");
    }
    
 
    /**
     * 根据最大值和最小值生成no表信息
     * @param minNo no最小值
     * @param maxNo no最大值
     */
    public void savesNo(Long minNo,Long maxNo) {
        synchronized (this) {
            if(noDao.selectByNo(minNo) == null) {
            	noDao.savesNo(minNo,maxNo);
            }
        }
    }
	
}