package com.cn.jm._dao.area;

import java.util.HashMap;
import java.util.List;

import com.cn._gen.dao.AreaDao;
import com.cn._gen.model.Area;
import com.cn.jm.core.utils.cache.JMCacheKit;

/**
 * Generated by 广州小跑robot.
 */
public class JMAreaDao extends AreaDao {

	public static final JMAreaDao jmd = new JMAreaDao();

	private static final int CHINA_ID = 100000;
	
	public List<Area> list(Integer leveltype,Integer parentId) {
		HashMap<String, Object> andpm = new HashMap<String, Object>();
		andpm.put("fz", 0);
		andpm.put("leveltype", leveltype);
		if (leveltype > 1) {
			andpm.put("parentid", parentId);
		}
		return list("", andpm, "id", DESC, true);
	}

	public List<Area> getByShengList() {
		HashMap<String, Object> andpm = new HashMap<String, Object>();
		andpm.put("fz", 0);
		andpm.put("leveltype", AreaEnum.PROVINCE_LEVELTYPE.getValue());
		andpm.put("parentid", CHINA_ID);
		
		return list("", andpm, "id", DESC, true);
	}
	
	public List<Area> getByShiList(int parentId) {
		HashMap<String, Object> andpm = new HashMap<String, Object>();
		andpm.put("fz", 0);
		andpm.put("leveltype", AreaEnum.CITY_LEVELTYPE.getValue());
		andpm.put("parentid", parentId);
		return list("", andpm, "id", DESC, true);
	}

	public List<Area> getByQuList(int parentId) {
		HashMap<String, Object> andpm = new HashMap<String, Object>();
		andpm.put("fz", 0);
		andpm.put("leveltype", AreaEnum.AREA_LEVELTYPE.getValue());
		andpm.put("parentid", parentId);
		return list("", andpm, "id", DESC, true);
	}
	
	/**
	 * 获取所有地域
	 * @return
	 */
	public List<Area> getAllList() {
		List<Area> shengList = getByShengList();
		for (int i = 0; i < shengList.size(); i++) {
			Area sheng = shengList.get(i);
			if (sheng != null) {
				List<Area> shiList = getByShiList(sheng.getId());
				sheng.put("nextList", shiList);
				for (int j = 0; j < shiList.size(); j++) {
					Area shi = shiList.get(j);
					if (shi != null) {
						List<Area> quList = getByQuList(shi.getId());
						shi.put("nextList", quList);
					}
				}
			}
		}
		return shengList;
	}
	
	public void clearCache() {
		JMCacheKit.removeAll("area");
	}

}
