
package com.cn.jm._dao.suggest;

import com.cn._gen.dao.SuggestDao;
import com.cn._gen.model.Suggest;
import com.cn.jm.util.SqlUtil;
import com.jfinal.kit.HashKit;
import com.jfinal.plugin.activerecord.Page;


/**
 * Generated by 广州小跑robot.
 */
public class JMSuggestDao extends SuggestDao{
	
	public Page<Suggest> page(Integer pageNumber, Integer pageSize,Integer id,String keyword,String startTime,String endTime,boolean isCache){
		StringBuilder selectSql = new StringBuilder("SELECT ts.id,ts.createTime,ts.contact,ts.content,tau.nick ");
		StringBuilder fromSql = new StringBuilder(" FROM tb_suggest ts INNER JOIN tb_account_user tau on tau.accountId = ts.accountId");
		fromSql.append(" :WHERE ");
		SqlUtil.addWhere(fromSql," AND ts.id = ",id);
		SqlUtil.addLike(fromSql," AND content","%",keyword,"%");
		SqlUtil.addBetweenTime(fromSql, startTime, endTime, " AND createTime");
		fromSql.append(" ORDER BY id DESC");
		SqlUtil.changeWhere(fromSql);
		String strFromSql = SqlUtil.getSql(fromSql);
		String strSelectSql = selectSql.toString();
		return isCache?dao.paginateByCache(cacheName,HashKit.md5(selectSql.append(strFromSql).toString()), pageNumber, pageSize,false,strSelectSql, strFromSql)
			:dao.paginate(pageNumber, pageSize, false, strSelectSql,strFromSql);
	}
	
}
