
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderGoods<M extends BaseOrderGoods<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setSkuId(java.lang.Integer skuId) {
		set("skuId", skuId);
	}

	public java.lang.Integer getSkuId() {
		return get("skuId");
	}

	public void setSkuCode(java.lang.String skuCode) {
		set("skuCode", skuCode);
	}

	public java.lang.String getSkuCode() {
		return get("skuCode");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goodsName");
	}

	public void setSkuImg(java.lang.String skuImg) {
		set("skuImg", skuImg);
	}

	public java.lang.String getSkuImg() {
		return get("skuImg");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setRefundOrderId(java.lang.Integer refundOrderId) {
		set("refundOrderId", refundOrderId);
	}

	public java.lang.Integer getRefundOrderId() {
		return get("refundOrderId");
	}

	public void setRefundNum(java.lang.Integer refundNum) {
		set("refundNum", refundNum);
	}

	public java.lang.Integer getRefundNum() {
		return get("refundNum");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}