
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseWebcastRoomManagement<M extends BaseWebcastRoomManagement<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("roomId");
	}

	public void setAnchorAccountId(java.lang.Integer anchorAccountId) {
		set("anchorAccountId", anchorAccountId);
	}

	public java.lang.Integer getAnchorAccountId() {
		return get("anchorAccountId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}