
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseMarketingGoods<M extends BaseMarketingGoods<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setMarketId(java.lang.Integer marketId) {
		set("marketId", marketId);
	}

	public java.lang.Integer getMarketId() {
		return get("marketId");
	}

	public void setFz(java.lang.Integer fz) {
		set("fz", fz);
	}

	public java.lang.Integer getFz() {
		return get("fz");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}