
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCollect<M extends BaseUserCollect<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setGoodsImg(java.lang.String goodsImg) {
		set("goodsImg", goodsImg);
	}

	public java.lang.String getGoodsImg() {
		return get("goodsImg");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goodsName");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOldprice(java.math.BigDecimal oldprice) {
		set("oldprice", oldprice);
	}

	public java.math.BigDecimal getOldprice() {
		return get("oldprice");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}