
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setParameter(java.lang.String parameter) {
		set("parameter", parameter);
	}

	public java.lang.String getParameter() {
		return get("parameter");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setArtNo(java.lang.String artNo) {
		set("artNo", artNo);
	}

	public java.lang.String getArtNo() {
		return get("artNo");
	}

	public void setTagprice(java.math.BigDecimal tagprice) {
		set("tagprice", tagprice);
	}

	public java.math.BigDecimal getTagprice() {
		return get("tagprice");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}

	public java.lang.String getYear() {
		return get("year");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public java.lang.String getThumbnail() {
		return get("thumbnail");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOldPrice(java.math.BigDecimal oldPrice) {
		set("oldPrice", oldPrice);
	}

	public java.math.BigDecimal getOldPrice() {
		return get("oldPrice");
	}

	public void setResalePrice(java.math.BigDecimal resalePrice) {
		set("resalePrice", resalePrice);
	}

	public java.math.BigDecimal getResalePrice() {
		return get("resalePrice");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setSellCount2(java.lang.Integer sellCount2) {
		set("sellCount2", sellCount2);
	}

	public java.lang.Integer getSellCount2() {
		return get("sellCount2");
	}

	public void setSellCount(java.lang.Integer sellCount) {
		set("sellCount", sellCount);
	}

	public java.lang.Integer getSellCount() {
		return get("sellCount");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public void setRecommend(java.lang.Integer recommend) {
		set("recommend", recommend);
	}

	public java.lang.Integer getRecommend() {
		return get("recommend");
	}

	public void setIshot(java.lang.Long ishot) {
		set("ishot", ishot);
	}

	public java.lang.Long getIshot() {
		return get("ishot");
	}

	public void setLabelId(java.lang.Integer labelId) {
		set("labelId", labelId);
	}

	public java.lang.Integer getLabelId() {
		return get("labelId");
	}

	public void setShopModId(java.lang.Integer shopModId) {
		set("shopModId", shopModId);
	}

	public java.lang.Integer getShopModId() {
		return get("shopModId");
	}

	public void setServiceType(java.lang.Integer serviceType) {
		set("serviceType", serviceType);
	}

	public java.lang.Integer getServiceType() {
		return get("serviceType");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("roomId");
	}

	public void setDel(java.lang.Integer del) {
		set("del", del);
	}

	public java.lang.Integer getDel() {
		return get("del");
	}

	public void setResaleNum(java.lang.Integer resaleNum) {
		set("resaleNum", resaleNum);
	}

	public java.lang.Integer getResaleNum() {
		return get("resaleNum");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setVideo(java.lang.String video) {
		set("video", video);
	}

	public java.lang.String getVideo() {
		return get("video");
	}

	public void setSellState(java.lang.Integer sellState) {
		set("sellState", sellState);
	}

	public java.lang.Integer getSellState() {
		return get("sellState");
	}

	public void setAccountType(java.lang.Integer accountType) {
		set("accountType", accountType);
	}

	public java.lang.Integer getAccountType() {
		return get("accountType");
	}



}