
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseBalanceRecord<M extends BaseBalanceRecord<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setIds(java.lang.Integer ids) {
		set("ids", ids);
	}

	public java.lang.Integer getIds() {
		return get("ids");
	}

	public void setSourceId(java.lang.Integer sourceId) {
		set("sourceId", sourceId);
	}

	public java.lang.Integer getSourceId() {
		return get("sourceId");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setCoinTypeId(java.lang.Integer coinTypeId) {
		set("coinTypeId", coinTypeId);
	}

	public java.lang.Integer getCoinTypeId() {
		return get("coinTypeId");
	}

	public void setMsgType(java.lang.Integer msgType) {
		set("msgType", msgType);
	}

	public java.lang.Integer getMsgType() {
		return get("msgType");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setCoinCode(java.lang.String coinCode) {
		set("coinCode", coinCode);
	}

	public java.lang.String getCoinCode() {
		return get("coinCode");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}