
package com.cn._gen.model;

import com.cn._gen.model.base.BaseMarketingGoods;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class MarketingGoods extends BaseMarketingGoods<MarketingGoods> {
	
	public static final MarketingGoods dao = new MarketingGoods().dao();
	
}