
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}

	public java.lang.Integer getParentid() {
		return get("parentid");
	}

	public void setShortname(java.lang.String shortname) {
		set("shortname", shortname);
	}

	public java.lang.String getShortname() {
		return get("shortname");
	}

	public void setLeveltype(java.lang.Integer leveltype) {
		set("leveltype", leveltype);
	}

	public java.lang.Integer getLeveltype() {
		return get("leveltype");
	}

	public void setCitycode(java.lang.String citycode) {
		set("citycode", citycode);
	}

	public java.lang.String getCitycode() {
		return get("citycode");
	}

	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}

	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}

	public java.lang.String getLng() {
		return get("lng");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}

	public java.lang.String getLat() {
		return get("lat");
	}

	public void setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
	}

	public java.lang.String getPinyin() {
		return get("pinyin");
	}

	public void setFz(java.lang.Integer fz) {
		set("fz", fz);
	}

	public java.lang.Integer getFz() {
		return get("fz");
	}



}