
package com.cn._gen.model;

import com.cn._gen.model.base.BaseFreightTemplate;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class FreightTemplate extends BaseFreightTemplate<FreightTemplate> {
	
	public static final FreightTemplate dao = new FreightTemplate().dao();
	
}