
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRoleMenu;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	
	public static final RoleMenu dao = new RoleMenu().dao();
	
}