
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setWeChatId(java.lang.String weChatId) {
		set("weChatId", weChatId);
	}

	public java.lang.String getWeChatId() {
		return get("weChatId");
	}

	public void setFaceBookId(java.lang.String faceBookId) {
		set("faceBookId", faceBookId);
	}

	public java.lang.String getFaceBookId() {
		return get("faceBookId");
	}

	public void setQqId(java.lang.String qqId) {
		set("qqId", qqId);
	}

	public java.lang.String getQqId() {
		return get("qqId");
	}

	public void setUserSig(java.lang.String userSig) {
		set("userSig", userSig);
	}

	public java.lang.String getUserSig() {
		return get("userSig");
	}

	public void setInvitationCode(java.lang.String invitationCode) {
		set("invitationCode", invitationCode);
	}

	public java.lang.String getInvitationCode() {
		return get("invitationCode");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parentId");
	}



}