
package com.cn._gen.model;

import com.cn._gen.model.base.BaseSuggest;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Suggest extends BaseSuggest<Suggest> {
	
	public static final Suggest dao = new Suggest().dao();
	
}