
package com.cn.jm.controller.base.system;

import com.cn._gen.model.Configure;
import com.cn.jm._dao.configure.ConfigureEnum;
import com.cn.jm.core.JMConsts;
import com.cn.jm.core.web.controller.JMBaseSystemController;
import com.cn.jm.interceptor.SystemLoginInterceptor;
import com.cn.jm.service.JMConfigService;
import com.cn.jm.util.JMResultUtil;
import com.cn.jm.web.core.router.JMRouterMapping;
import com.jfinal.aop.Before;
import com.jfinal.aop.Inject;

/**
 * Generated by 广州小跑robot.
 */
@JMRouterMapping(url = SystemConfigController.url)
@Before(value={SystemLoginInterceptor.class})
public class SystemConfigController extends JMBaseSystemController {
	
	public static final String path = JMConsts.base_view_url+"/system/base/config";
	public static final String url ="/system/config";
	
	@Inject
	public JMConfigService configService;
	
	public void invitationReward() {
		Configure configure = configService.selectOneByKeyAndValue("name =", ConfigureEnum.INVITATION_REWARD.getName());
		setAttr("configure", configure);
		render(path + "/invitationReward.html");
	}
	
	public void update() {
		Configure configure = getModel(Configure.class);
		configService.update(configure);
		JMResultUtil.success().renderJson(this);
	}
}