
package com.cn.jm._dao.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.cn._gen.dao.OrderDao;
import com.cn._gen.model.Account;
import com.cn._gen.model.Address;
import com.cn._gen.model.Goods;
import com.cn._gen.model.GoodsCart;
import com.cn._gen.model.GoodsResale;
import com.cn._gen.model.Order;
import com.cn._gen.model.OrderGoods;
import com.cn._gen.model.RefundGoods;
import com.cn._gen.model.RefundOrder;
import com.cn._gen.model.Sku;
import com.cn.jm._dao._base.common.JMCommonDao;
import com.cn.jm._dao.account.AccountEnum;
import com.cn.jm._dao.account.JMAccountDao;
import com.cn.jm._dao.address.JMAddressDao;
import com.cn.jm._dao.goods.GoodsEnum;
import com.cn.jm._dao.goods.JMGoodsCartDao;
import com.cn.jm._dao.goods.JMGoodsDao;
import com.cn.jm._dao.goods.JMGoodsStarDao;
import com.cn.jm._dao.refund.JMRefundGoodsDao;
import com.cn.jm._dao.refund.JMRefundOrderDao;
import com.cn.jm._dao.sku.JMSkuDao;
import com.cn.jm.core.JMMessage;
import com.cn.jm.core.db.JMToolSql;
import com.cn.jm.core.tool.JMToolString;
import com.cn.jm.core.tool.ToolTimer;
import com.cn.jm.core.utils.util.JMResult;
import com.cn.jm.core.utils.util.NoUtils;
import com.cn.jm.information.PromptInformationEnum;
import com.cn.jm.service.JMAccountUserService;
import com.cn.jm.service.JMBalanceRecordService;
import com.cn.jm.service.JMGoodsResaleService;
import com.cn.jm.service.JMOrderService;
import com.cn.jm.util.JMResultUtil;
import com.cn.jm.util.SqlUtil;
import com.cn.jm.util.KdniaoTrackQueryAPI;
import com.jfinal.aop.Before;
import com.jfinal.aop.Inject;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.jfinal.plugin.redis.Cache;
import com.jfinal.plugin.redis.Redis;

import redis.clients.jedis.Jedis;

/**
 * Generated by 广州小跑robot.
 */
public class JMOrderDao extends OrderDao {

	@Inject
	public JMCommonDao commonDao;
	@Inject
	public JMGoodsDao goodsDao;
	@Inject
	public JMOrderGoodsDao orderGoodsDao;
	@Inject
	public JMAccountDao jmAccountDao;
	@Inject
	public JMSkuDao skuDao;
	@Inject
	public JMAddressDao addressDao;
	@Inject
	public JMGoodsCartDao goodsCartDao;
	@Inject
	public JMRefundOrderDao refundOrderDao;
	@Inject
	public JMRefundGoodsDao refundGoodsDao;
	@Inject
	public JMGoodsStarDao goodsStarDao ;
	@Inject
	JMGoodsResaleService goodsResaleService;
	@Inject
	JMAccountUserService accountUserService; 
	@Inject
	JMBalanceRecordService balanceRecordService;

	public static final int BUY_NOW = 0;

	public static final int BUY_CART = 1;

	public static final int REFUND_ONLY_MONEY = 0;// 仅退款

	public static final int REFUND_MONEY_GOODS = 1;// 退货退款

	public static final String REDIS_ORDER = "order";

	public static final String GOODS_ORDER = "G";

	public static final String REFUND_ORDER = "R";

	public static final String NOPAY_LIST = "NOPAY_LIST";// 未付款订单
	/**
	 * 取消订单
	 */
	public static final int CANCEL = 6;

	/**
	 * 已发货
	 */
	public static final int DELIVERED = 7;

	/**
	 * 
	 * @date 2019年6月20日 下午12:06:54
	 * @author JaysonLee
	 * @Description: 立即购买订单
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param goodsId
	 * @param num
	 * @param addressId
	 * @param userId
	 * @param skuId
	 * @param remark
	 * @return
	 * @throws Exception
	 *
	 */
	@Before(Tx.class)
	public JMResult create(int goodsId, Integer addressId, Account user, String remark, Integer resaleAccountId, OrderState orderType) throws Exception {
		Goods goods = goodsDao.getById(goodsId);
		if (goods == null) {
			return JMResult.create().code(JMResult.FAIL).desc("商品不存在");
		}
		if(goods.getUserId().equals(user.getId())) {
			return JMResultUtil.fail(PromptInformationEnum.NOT_PURCHASE_ME_GOODS);
		}
		if(GoodsEnum.NOT_SELL_STATE.identical(goods.getSellState())) {
			return JMResultUtil.fail(PromptInformationEnum.GOODS_FORM_TIES);
		}
		if (goods.getState() == 0) {
			String no = NoUtils.createOutTradeNo(GOODS_ORDER);// 订单号
			Order order = new Order();
			order.setOrderNo(no);
			order.setAccountId(user.getId());
			order.setDesc(remark);
			order.setType(BUY_NOW);
			order.setCreateTime(new Date());
			order.setState(0);
			setOrderAddress(addressId, order);
			order.setMoney(goods.getPrice());
			order.setOriginalPrice(goods.getPrice());
			order.setGoodsId(goodsId);
			order.setOrderType(orderType.getCode());
			if(resaleAccountId != null)
				order.setResaleAccountId(resaleAccountId);

			if (save(order)) {
				OrderGoods orderGoods = new OrderGoods();
				orderGoods.setOrderId(order.getId());
				orderGoods.setOrderNo(order.getOrderNo());
				orderGoods.setGoodsId(goods.getId());
				orderGoods.setGoodsName(goods.getName());
				orderGoods.setSkuImg(goods.getThumbnail());
				orderGoods.setNum(1);
				orderGoods.setPrice(goods.getPrice());
				orderGoods.setState(0);
				orderGoods.setCreateTime(new Date());
				orderGoods.setSkuId(goodsId);//暂时将skuId设置为商品id
				orderGoodsDao.save(orderGoods);

				// 塞进定时器队列
				Cache cache = Redis.use();
				Jedis jedis = cache.getJedis();

				try {
					jedis.select(1);
					jedis.setex(order.getOrderNo(), 3600 * 24, order.getId().toString());
				} finally {
					cache.close(jedis);
				}

				return JMResult.create().code(JMResult.SUCCESS).data(order.getOrderNo()).desc("创建订单成功");
			} else {
				throw new Exception("保存订单失败");
			}
		} else {
			return JMResult.create().code(JMResult.FAIL).desc("该商品已下架");
		}
	}
	
	public JMResult create(int goodsId, Integer addressId, Integer accountId, String remark, Integer resaleAccountId, OrderState orderType) throws Exception {
		Account account = jmAccountDao.getById(accountId);
		return create(goodsId, addressId, account, remark, resaleAccountId, orderType);
	}
	
	/**
	 * 创建转售订单
	 * @param goodsResaleId
	 * @param addressId
	 * @param account
	 * @param remark
	 * @return
	 * @throws Exception 
	 */
	public JMResult createResaleOrder(int goodsResaleId, int addressId, Account account, String remark) throws Exception {
		GoodsResale goodsResale = goodsResaleService.selectById(goodsResaleId);
		
		if(goodsResale == null) {
			return JMResultUtil.fail(PromptInformationEnum.GOODS_NOT_EXISTENCE);
		}
		if(account.getId().equals(goodsResale.getAccountId())) {
			return JMResultUtil.fail(PromptInformationEnum.NOT_PURCHASE_ME_GOODS);
		}
		return create(goodsResale.getGoodsId(), addressId, account, remark, goodsResale.getAccountId(), OrderState.SHOP_ORDER_TYPE);
	}
	
	public void setOrderAddress(Integer addressId, Order order) {
		if(addressId != null) {
			Address address = addressDao.getById(addressId);
			if (address != null) {
				order.setAddress(address.getSheng() + address.getShi() + address.getQu() + address.getAddress());
				order.setAddressName(address.getName());
				order.setAddressPhone(address.getMobile());
			}
		}
	}
	// /**
	// *
	// * @date 2019年6月20日 下午12:06:54
	// * @author JaysonLee
	// * @Description: 立即购买订单
	// * @reqMethod post
	// * @paramter
	// * @pDescription
	// * @param goodsId
	// * @param num
	// * @param addressId
	// * @param userId
	// * @param skuId
	// * @param remark
	// * @return
	// * @throws Exception
	// *
	// */
	// @Before(Tx.class)
	// public JMResult create(int goodsId, int num, int addressId, int userId,int
	// skuId,String remark) throws Exception{
	// Account user = jmAccountDao.getById(userId);
	// if(user == null || user.getState() != 0){
	// return JMResult.create().code(JMResult.FAIL).desc("用户不可用");
	// }
	// num = num <= 0 ? 1 : num;
	// Goods goods = goodsDao.getById(goodsId);
	// if(goods == null){
	// return JMResult.create().code(JMResult.FAIL).desc("商品不存在");
	// }
	// Sku sku = skuDao.getByIdAndGoodsId(goodsId,skuId);
	// if(sku == null){
	// return JMResult.create().code(JMResult.FAIL).desc("商品规格不存在");
	// }
	// if(goods.getState() == 0){
	// Address address= addressDao.getById(addressId);
	// if(address != null && address.getUserId().equals(userId)){
	// String no = NoUtils.createOutTradeNo(GOODS_ORDER);//订单号
	// Order order = new Order();
	// order.setOrderNo(no);
	// order.setAccountId(userId);
	// order.setDesc(remark);
	// order.setType(BUY_NOW);
	// order.setCreateTime(new Date());
	// order.setState(0);
	// order.setAddress(address.getSheng()+address.getShi()+address.getQu()+address.getAddress());
	// order.setAddressName(address.getName());
	// order.setAddressPhone(address.getMobile());
	// order.setMoney(sku.getPrice().multiply(new BigDecimal(num)));
	//
	// //算运费
	// JSONObject jsonObject =
	// JSONObject.parseObject("{\"skuList\":[{\"num\":"+num+",\"skuId\":"+skuId+"}]}");
	// JSONArray array = jsonObject.getJSONArray("skuList");
	// List<GoodsCart> goodsCards = array.toJavaList(GoodsCart.class);
	// if (CollectionsUtils.isEmpty(goodsCards)) {
	// return JMResult.fail(this,"请选择商品");
	// }
	//// JMResult freightResult = freightService.calculationFreight(addressId,
	// goodsCards, userId);
	//// if(freightResult.getCode() != JMResult.SUCCESS) {
	//// return freightResult ;
	//// }
	//
	//// HashMap<String,Object> dataHashMap = (HashMap<String, Object>)
	// freightResult.getData();
	////
	//// BigDecimal freightBigDecimal = (BigDecimal) dataHashMap.get("freight");
	////
	//// order.setFreight(freightBigDecimal);//运费
	//// order.setMoney(order.getMoney().add(freightBigDecimal));//总额加上运费
	// order.setMoney(order.getMoney());//总额加上运费
	//
	// if(save(order)){
	// OrderGoods orderGoods = new OrderGoods();
	// orderGoods.setOrderId(order.getId());
	// orderGoods.setOrderNo(order.getOrderNo());
	// orderGoods.setGoodsId(goods.getId());
	// orderGoods.setSkuId(skuId);
	// orderGoods.setSkuCode(sku.getSkuCode());
	// orderGoods.setGoodsName(goods.getName());
	// orderGoods.setSkuImg(sku.getImage());
	// orderGoods.setNum(num);
	// orderGoods.setPrice(sku.getPrice());
	// orderGoods.setState(0);
	// orderGoods.setCreateTime(new Date());
	// orderGoodsDao.save(orderGoods);
	//
	// sku.setStock(sku.getStock() - num);
	// skuDao.update(sku);
	//
	// //塞进定时器队列
	// Cache cache = Redis.use();
	// Jedis jedis = cache.getJedis();
	//
	// try{
	// jedis.select(1);
	// jedis.setex(order.getOrderNo(),3600*24,order.getId().toString());
	// }finally{
	// cache.close(jedis);
	// }
	//
	//
	// return
	// JMResult.create().code(JMResult.SUCCESS).data(order.getOrderNo()).desc("创建订单成功");
	// }else{
	// throw new Exception("保存订单失败");
	// }
	// }else{
	// return JMResult.create().code(JMResult.FAIL).desc("收货地址不正确");
	// }
	// }else{
	// return JMResult.create().code(JMResult.FAIL).desc("该商品已下架");
	// }
	// }

	/**
	 * 
	 * @date 2019年6月20日 下午12:07:08
	 * @author JaysonLee
	 * @Description: 购物车购买订单
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param cartIds
	 * @param addressId
	 * @param userId
	 * @param remark
	 * @return
	 * @throws Exception
	 *
	 */
	@Before(Tx.class)
	public JMResult createCartOrder(String cartIds, int addressId, int userId, String remark) throws Exception {
		Account user = jmAccountDao.getById(userId);
		if (user == null || user.getState() != 0) {
			return JMResult.create().code(JMResult.FAIL).desc("用户不可用");
		}

		String carIdStr[] = cartIds.split(",");
		List<OrderGoods> orderGoodsList = new ArrayList<>();
		BigDecimal money = BigDecimal.ZERO;
		List<GoodsCart> listGoodsCarts = new ArrayList<>();
		for (String cartId : carIdStr) {
			GoodsCart goodsCart = goodsCartDao.getById(Integer.valueOf(cartId));

			Goods goods = goodsDao.getById(goodsCart.getGoodsId(), false);
			if (goods == null) {
				return JMResult.create().code(JMResult.FAIL).desc("商品不存在");
			}
			Sku sku = skuDao.getByIdAndGoodsId(goodsCart.getGoodsId(), goodsCart.getSkuId());
			if (sku == null) {
				return JMResult.create().code(JMResult.FAIL).desc("商品规格不存在");
			}
			if (sku.getStock() < goodsCart.getNum()) {
				return JMResult.create().code(JMResult.FAIL).desc(goodsCart.getName() + sku.getSkuCode() + "商品规格库存不足");
			}

			if (goods.getState() == 0) {

				OrderGoods orderGoods = new OrderGoods();
				orderGoods.setGoodsId(goods.getId());
				orderGoods.setSkuId(goodsCart.getSkuId());
				orderGoods.setSkuCode(sku.getSkuCode());
				orderGoods.setGoodsName(goods.getName());
				orderGoods.setSkuImg(sku.getImage());
				orderGoods.setNum(goodsCart.getNum());
				orderGoods.setPrice(goodsCart.getPrice());
				orderGoods.setState(0);
				orderGoods.setCreateTime(new Date());

				sku.setStock(sku.getStock() - goodsCart.getNum());
				skuDao.update(sku);
				orderGoodsList.add(orderGoods);

				money = money.add(goodsCart.getPrice().multiply(new BigDecimal(goodsCart.getNum())));
				// 算邮费用的
				listGoodsCarts.add(goodsCart.remove("id", "goodsId", "userId", "price", "name", "image", "createTime"));
			} else {
				return JMResult.create().code(JMResult.FAIL).desc("该商品已下架");
			}

		}

		Address address = addressDao.getById(addressId);
		if (address != null && address.getUserId().equals(userId)) {
			String no = NoUtils.createOutTradeNo(GOODS_ORDER);// 订单号
			Order order = new Order();
			order.setOrderNo(no);
			order.setAccountId(userId);
			order.setDesc(remark);
			order.setType(BUY_CART);
			order.setCreateTime(new Date());
			order.setState(0);
			order.setAddress(address.getSheng() + address.getShi() + address.getQu() + address.getAddress());
			order.setAddressName(address.getName());
			order.setAddressPhone(address.getMobile());

			order.setMoney(money);
			// //计算邮费
			// JMResult freightResult = freightService.calculationFreight(addressId,
			// listGoodsCarts, userId);
			// if(freightResult.getCode() != JMResult.SUCCESS) {
			// return freightResult ;
			// }
			//
			// HashMap<String,Object> dataHashMap = (HashMap<String, Object>)
			// freightResult.getData();
			//
			// BigDecimal freightBigDecimal = (BigDecimal) dataHashMap.get("freight");
			//
			// order.setFreight(freightBigDecimal);//运费
			// order.setMoney(order.getMoney().add(freightBigDecimal));//总额加上运费
			order.setMoney(order.getMoney());// 总额加上运费

			if (save(order)) {
				for (OrderGoods orderGoods : orderGoodsList) {
					orderGoods.setOrderId(order.getId());
					orderGoods.setOrderNo(order.getOrderNo());
					orderGoodsDao.save(orderGoods);
				}
				goodsCartDao.del(userId, cartIds);// 删除购物车

				// 塞进队列
				Cache cache = Redis.use();
				Jedis jedis = cache.getJedis();

				try {
					jedis.select(1);
					jedis.setex(order.getOrderNo(), 3600 * 24, order.getId().toString());
				} finally {
					cache.close(jedis);
				}

				return JMResult.create().code(JMResult.SUCCESS).data(order.getOrderNo()).desc("创建订单成功");
			} else {
				throw new Exception("保存订单失败");
			}
		} else {
			return JMResult.create().code(JMResult.FAIL).desc("收货地址不正确");
		}

	}

	public Page<Order> pageMy(int pageNumber, int pageSize, int state, int accountId) {
		StringBuilder fromSql = new StringBuilder(" FROM shop_order WHERE isDel = 0")
			.append(" AND accountId = ").append(accountId);
		if(state == 0) {
			fromSql.append(" AND state IN (0,1)");
		}else if(state == 8) {
			fromSql.append(" AND state IN (8,9)");
		}else if(state != -1) {
			fromSql.append(" AND state = ").append(state);
		}
		fromSql.append(" ORDER BY id DESC");
		Page<Order> page = dao.paginate(pageNumber, pageSize, false, "SELECT *", fromSql.toString());
		for (Order order : page.getList()) {
			order.put("goodsList", orderGoodsDao.listByOrderId(order.getId()));
		}
		return page;
	}

	/**
	 * 
	 * @date 2019年2月18日 上午9:19:40
	 * @author JaysonLee
	 * @Description: 订单详情
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param userId
	 * @param orderId
	 * @return
	 *
	 */
	public Order detail(int userId, int orderId) {
		HashMap<String, Object> andpm = new HashMap<>();
		andpm.put("accountId", userId);
		andpm.put("isDel", 0);
		andpm.put("id", orderId);
		Order order = get(andpm, false);
		if (order != null) {
			order.put("goodsList", orderGoodsDao.listByOrderId(order.getId()));
			order.put("goodsComment", goodsStarDao.getByGoodsId(order.getGoodsId(), userId));// 商品评论
		}
		return order;
	}

	/**
	 * 
	 * @date 2019年2月18日 上午9:19:40
	 * @author JaysonLee
	 * @Description: 订单详情
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param userId
	 * @param orderId
	 * @return
	 *
	 */
	public Order detail(int orderId) {
		HashMap<String, Object> andpm = new HashMap<>();
		andpm.put("isDel", 0);
		andpm.put("id", orderId);
		Order order = get(andpm, false);
		if (order != null) {
			order.put("goodsList", orderGoodsDao.listByOrderId(order.getId()));
		}
		return order;
	}
	
	/**
	 * 
	 * @date 2019年2月18日 上午9:57:38
	 * @author JaysonLee
	 * @Description: 前端用户删除订单
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param userId
	 * @param orderId
	 * @return
	 *
	 */
	public boolean delOrder(int userId, int orderId) {
		HashMap<String, Object> andpm = new HashMap<>();
		andpm.put("accountId", userId);
		andpm.put("isDel", 0);
		andpm.put("id", orderId);
		Order order = get(andpm, false);
		if (order != null) {
			order.setIsDel(1);// 删除状态
			return update(order);
		}
		return false;
	}

	public JMResult cancel(int userId, int orderId) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("accountId", userId);
		param.put("id", orderId);
		param.put("state", 0);
		Order order = get(param, false);
		if (order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("非法操作，无效订单");
		}
//		order.setState(CANCEL);// 取消订单
//		if (update(order)) {
		return JMResult.create().code(JMResult.SUCCESS).desc("取消订单成功");
//		}
//		return JMResult.create().code(JMResult.FAIL).desc("操作失败");
	}

	public boolean cancelByNo(String no) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("orderNo", no);
		param.put("state", 0);
		Order order = get(param, false);
		if (order != null) {
			order.setState(CANCEL);// 取消订单
			return update(order);
		}
		return false;
	}

	/**
	 * 
	 * @date 2019年1月8日 上午11:40:05
	 * @author JaysonLee
	 * @Description: 自动处理退款
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param no
	 * @return
	 *
	 */
	public boolean automaticRefund(String no) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("no", no);
		param.put("state", 0);
		RefundOrder refundOrder = refundOrderDao.get(param, false);
		if (refundOrder != null) {// 申请未处理的
			Order order = getById(refundOrder.getOrderId());
			JMResult jmResult = new JMOrderService().doubleBack(order, refundOrder.getMoney(), order.getAccountId());
			if (jmResult.getCode() != JMResult.SUCCESS) {// 退款不成功
				return false;
			}
			order.setState(5);// 已退款
			order.setRefundState(2);// 已处理退款
			update(order);

			refundOrder.setState(10);// 系统自动处理退款
			refundOrder.setRefundTime(new Date());
			refundOrderDao.update(refundOrder);

			Db.update("update shop_order_goods set state = 3 where state = 2 and orderId = ?",
					refundOrder.getOrderId());

			return true;
		} else {// 其他情况的
			param.put("state", 6);
			param.put("type", 1);// 退货退款的
			refundOrder = refundOrderDao.get(param, false);// 已上传物流单号的
			if (refundOrder != null) {
				Order order = getById(refundOrder.getOrderId());
				JMResult jmResult = new JMOrderService().doubleBack(order, refundOrder.getMoney(),
						order.getAccountId());
				if (jmResult.getCode() != JMResult.SUCCESS) {// 退款不成功
					return false;
				}
				order.setState(5);// 已退款
				order.setRefundState(2);// 已处理退款
				update(order);

				refundOrder.setState(10);// 系统自动处理退款
				refundOrder.setRefundTime(new Date());
				refundOrderDao.update(refundOrder);

				Db.update("update shop_order_goods set state = 3 where state = 2 and orderId = ?",
						refundOrder.getOrderId());

				return true;
			}
		}
		return false;
	}

	/**
	 * 
	 * @date 2019年1月28日 下午4:25:29
	 * @author JaysonLee
	 * @Description: 自动确认收货
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param no
	 * @return
	 *
	 */
	public boolean automaticReceived(String no) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("no", no);
		param.put("state", 7);
		Order order = get(param, false);
		if (order != null) {
			order.setState(8);// 确认收货
			return update(order);
		}
		return false;
	}

//	public Order getByOrderNO(String no) {
//		HashMap<String, Object> param = new HashMap<>();
//		param.put("orderNo", no);
//		param.put("state", 0);
//		Order order = get(param, false);
//		return order;
//	}
	
	public Order getByOrderNO(String no) {
		return dao.findFirst("SELECT * FROM shop_order WHERE orderNo = ? AND (state = 0 OR state = 1)", no);
	}
	
	public Order getByOrderNo(String orderNo) {
		return dao.findFirst("SELECT * FROM shop_order WHERE orderNo = ?",orderNo);
	}
	

	/**
	 * 
	 * @date 2019年1月4日 下午4:03:28
	 * @author JaysonLee
	 * @Description: 仅退款全部申请（发货前）
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param orderId
	 * @param accountId
	 * @param reason
	 * @return
	 *
	 */
	public JMResult toRefundAll(int orderId, int accountId, String reason) {
		LinkedHashMap<String, Object> param = new LinkedHashMap<>();
		param.put("id=", orderId);
		param.put("and accountId=", accountId);
		JMCommonDao.putIn(param, "and state", "2");

		Order order = commonDao.selectOne(Order.class, param);

		if (order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}

//		order.setState(4);// 退款中 不修改原本值
		order.setRefundState(OrderState.IN_AFTER_REFUND_STATE.getCode());// 订单存在售后
		update(order);

		RefundOrder refundOrder = new RefundOrder();
		refundOrder.setNo(NoUtils.createOutTradeNo(REFUND_ORDER));// 退款订单号
		refundOrder.setState(0);// 申请中
		refundOrder.setType(REFUND_ONLY_MONEY);
		refundOrder.setReason(reason);
		refundOrder.setOrderId(orderId);
		refundOrder.setMoney(order.getMoney());
		refundOrder.setUserId(accountId);
		refundOrder.setCreateTime(new Date());
		refundOrderDao.save(refundOrder);

		List<OrderGoods> orderGoodsList = orderGoodsDao.listByOrderId(order.getId());
		for (OrderGoods orderGoods : orderGoodsList) {
			orderGoods.setRefundNum(orderGoods.getNum());
			orderGoods.setState(2);// 仅退款中
			orderGoods.setRefundOrderId(refundOrder.getId());
			orderGoodsDao.update(orderGoods);

			RefundGoods refundGoods = new RefundGoods();
			refundGoods.setRefundNo(refundOrder.getNo());
			refundGoods.setRefundOrderId(refundOrder.getId());
			refundGoods.setGoodsId(orderGoods.getGoodsId());
			refundGoods.setSkuCode(orderGoods.getSkuCode());
//			refundGoods.setSkuId(orderGoods.getSkuId());
			refundGoods.setSkuImg(orderGoods.getSkuImg());
			refundGoods.setGoodsName(orderGoods.getGoodsName());
			refundGoods.setOrderGoodsId(orderGoods.getId());
			refundGoods.setPrice(orderGoods.getPrice());
			refundGoods.setRefundNum(orderGoods.getRefundNum());
			refundGoods.setCreateTime(new Date());
			refundGoodsDao.save(refundGoods);
		}

		// 定时
		Cache cache = Redis.use();
		Jedis jedis = cache.getJedis();

		try {
			jedis.select(1);
			jedis.setex(refundOrder.getNo(), 3600 * 24 * 3, refundOrder.getId().toString());
		} finally {
			cache.close(jedis);
		}

		return JMResult.create().code(JMResult.SUCCESS).desc("申请退款成功，请耐心等待商家处理");

	}

	/**
	 * 
	 * @date 2019年1月4日 下午5:53:09
	 * @author JaysonLee
	 * @Description: 处理仅退款订单
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param refundId
	 * @param state
	 *            1已通过等待退款（针对仅退款）2不通过申请5已通过等待上传物流单号退货
	 * @param refusedReason
	 * @return
	 *
	 */
	public JMResult dealAllRefund(int refundId, int state, String refusedReason) {
		LinkedHashMap<String, Object> param = new LinkedHashMap<>();
		param.put("id=", refundId);
		param.put("and state=", 0);// 申请中
		if (state == 1 || state == 2) {
			JMCommonDao.putIn(param, "and type", "0,2");// 仅退款情况下
		} else if (state == 5) {
			JMCommonDao.putIn(param, "and type", "1,2");// 退货退款情况下
		} else {
			return JMResult.create().code(JMResult.FAIL).desc("非法操作--状态异常");
		}
		RefundOrder refundOrder = commonDao.selectOne(RefundOrder.class, param);
		if (refundOrder == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}
		Order order = getById(refundOrder.getOrderId());

		refundOrder.setState(state);
		refundOrder.setAuditTime(new Date());
		if (JMToolString.isNotEmpty(refusedReason)) {
			refundOrder.setRefuseReason(refusedReason);
		}
		order.setRefundState(OrderState.AFTER_SUCCESS_REFUND_STATE.getCode());
		if (state == 1) {// 同意状态下,等待退款
			JMResult jmResult = new JMOrderService().doubleBack(order, refundOrder.getMoney(), order.getAccountId());
			if (jmResult.getCode() != JMResult.SUCCESS) {
				return jmResult;
			}
			order.setState(OrderState.AFTER_SUCCESS_STATE.getCode());// 已退款
			refundOrder.setState(4);// 已退款
			refundOrder.setRefundTime(new Date());
			refundOrderDao.update(refundOrder);

			Db.update("update shop_order_goods set state = 3 where state = 2 and orderId = ?",
					refundOrder.getOrderId());
			update(order);
			refundOrderDao.update(refundOrder);
			return JMResult.create().code(JMResult.SUCCESS).desc("操作成功");
		}
		refundOrderDao.update(refundOrder);
		update(order);
		return JMResult.create().code(JMResult.SUCCESS).desc("操作成功");
	}

	/**
	 * 
	 * @date 2019年1月7日 下午7:04:22
	 * @author JaysonLee
	 * @Description: 处理退货退款
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param refundId
	 * @param state
	 *            7上传物流单号后不通过8上传物流单号后通过等待退款
	 * @param refusedReason
	 * @return
	 *
	 */
	public JMResult dealGoodsRefund(int refundId, int state, String refusedReason) {
		LinkedHashMap<String, Object> param = new LinkedHashMap<>();
		param.put("id=", refundId);
		param.put("and state=", state == 5 || state == 2 ? 0 : 6);// 已上传物流单号
		param.put("and type=", 1);// 退货退款状态
		RefundOrder refundOrder = commonDao.selectOne(RefundOrder.class, param);
		if (refundOrder == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}
		refundOrder.setState(state);
		refundOrder.setAuditTime(new Date());
		if (JMToolString.isNotEmpty(refusedReason)) {
			refundOrder.setRefuseReason(refusedReason);
		}
		refundOrderDao.update(refundOrder);
		Order order = getById(refundOrder.getOrderId());
		order.setRefundState(OrderState.AFTER_SUCCESS_REFUND_STATE.getCode());
		if (state == 8) {// 同意状态下,等待退款
			JMResult jmResult = new JMOrderService().doubleBack(order, refundOrder.getMoney(), order.getAccountId());
			if (jmResult.getCode() != JMResult.SUCCESS) {
				return jmResult;
			}
			order.setState(OrderState.AFTER_SUCCESS_STATE.getCode());// 已退款
			refundOrder.setState(4);// 已退款
			refundOrder.setRefundTime(new Date());
			refundOrderDao.update(refundOrder);

			Db.update("update shop_order_goods set state = 3 where state = 2 and orderId = ?",
					refundOrder.getOrderId());
		}
		update(order);
		return JMResult.create().code(JMResult.SUCCESS).desc("操作成功");
	}

	/**
	 * 
	 * @date 2019年1月5日 上午10:19:25
	 * @author JaysonLee
	 * @Description: 申请退货退款订单
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param accountId
	 * @param ids
	 * @param orderId
	 * @param reason
	 * @param logisticsNo
	 * @param img1
	 * @param img2
	 * @param img3
	 * @param img4
	 * @param img5
	 * @param img6
	 * @return
	 *
	 */
	public JMResult toRefunds(int accountId, String ids, int orderId, String reason, List<String> imglist, int type) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("id", orderId);
		param.put("accountId", accountId);
		param.put("state", 7);// 已发货
		Order order = get(param, false);
		if (order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}

		RefundOrder refundOrder = new RefundOrder();
		refundOrder.setNo(NoUtils.createOutTradeNo(REFUND_ORDER));// 退款订单号
		refundOrder.setState(0);// 申请中
		refundOrder.setReason(reason);
		refundOrder.setType(type);// 0仅退款（发货前）1退货退款 2仅退款（发货后未收到货）
		refundOrder.setUserId(accountId);
		refundOrder.setOrderId(orderId);
		if (reason != null) {
			refundOrder.setReason(reason);
		}
		for (int i = 0; i < imglist.size(); i++) {
			String img = imglist.get(i);
			if (img != null) {
				refundOrder.set("img" + (i + 1), img);
			}
		}
		refundOrder.setCreateTime(new Date());
		refundOrderDao.save(refundOrder);

		BigDecimal money = BigDecimal.ZERO;// 该退的钱
		String id_nums[] = ids.split(",");
		for (String id_num : id_nums) {
			String idNum[] = id_num.split("_");
			Integer orderGoodsId = Integer.valueOf(idNum[0]);
			int num = Integer.valueOf(idNum[1]);

			OrderGoods orderGoods = orderGoodsDao.getById(orderGoodsId);

			orderGoods.setRefundNum(1);
			orderGoods.setState(1);// 退货退款中
			orderGoods.setRefundOrderId(refundOrder.getId());
			orderGoodsDao.update(orderGoods);

			RefundGoods refundGoods = new RefundGoods();
			refundGoods.setRefundNo(refundOrder.getNo());
			refundGoods.setRefundOrderId(refundOrder.getId());
			refundGoods.setGoodsId(orderGoods.getGoodsId());
			refundGoods.setSkuCode(orderGoods.getSkuCode());
			refundGoods.setSkuId(orderGoods.getSkuId());
			refundGoods.setSkuImg(orderGoods.getSkuImg());
			refundGoods.setGoodsName(orderGoods.getGoodsName());
			refundGoods.setPrice(orderGoods.getPrice());
			refundGoods.setRefundNum(num);
			refundGoods.setOrderGoodsId(orderGoods.getId());
			refundGoods.setCreateTime(new Date());
			refundGoodsDao.save(refundGoods);

			money = money.add((refundGoods.getPrice().multiply(new BigDecimal(num))));
		}
		refundOrder.setMoney(money);
		refundOrderDao.update(refundOrder);
		order.setRefundState(1);// 订单存在售后
		update(order);
		// 七天定时
		Cache cache = Redis.use();
		Jedis jedis = cache.getJedis();

		try {
			jedis.select(1);
			jedis.setex(refundOrder.getNo(), 3600 * 24 * 7, refundOrder.getId().toString());
		} finally {
			cache.close(jedis);
		}

		return JMResult.create().code(JMResult.SUCCESS).desc("申请退款成功，请耐心等待商家处理");

	}

	/**
	 * 
	 * @date 2019年1月7日 下午7:33:31
	 * @author JaysonLee
	 * @Description: 上传物流单号
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param refundOrderId
	 * @param logisticsNo
	 * @param accountId
	 * @return
	 *
	 */
	public JMResult refundLogisticsNo(int refundOrderId, String logisticsNo, int accountId) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("id", refundOrderId);
		param.put("userId", accountId);
		param.put("type", 1);
		param.put("state", 5);
		RefundOrder refundOrder = refundOrderDao.get(param, false);
		if (refundOrder == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}
		refundOrder.setLogisticsNo(logisticsNo);
		// 物流公司自动识别待后
		refundOrder.setLogisticsName("");
		refundOrder.setState(6);// 已上传物流单号
		refundOrderDao.update(refundOrder);
		// 七天二次倒计时
		Cache cache = Redis.use();
		Jedis jedis = cache.getJedis();

		try {
			jedis.select(1);
			jedis.setex(refundOrder.getNo(), 3600 * 24 * 7, refundOrder.getId().toString());
		} finally {
			cache.close(jedis);
		}

		return JMResult.create().code(JMResult.SUCCESS).desc("上传单号成功，请耐心等待商家处理");
	}

	/**
	 * 
	 * @date 2019年1月8日 下午4:39:32
	 * @author JaysonLee
	 * @Description: 确认收货
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param accountId
	 * @param orderId
	 * @return
	 *
	 */
	public JMResult confirmReceipt(int accountId, int orderId) {
		LinkedHashMap<String, Object> param = new LinkedHashMap<>();
		param.put("id=", orderId);
		param.put("and accountId=", accountId);
		JMCommonDao.putIn(param, "and state", "7,10");
		Order order = commonDao.selectOne(Order.class, param);
		if (order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("没有此订单");
		}
		order.setState(OrderState.TO_BE_EVALUATED_STATE.getCode());
		order.setFinishTime(new Date());
		
		if (update(order)) {
			balanceRecordService.confirmReceipt(order);
			return JMResult.create().code(JMResult.SUCCESS).desc("确认收货成功");
		}
		return JMResult.create().code(JMResult.FAIL).desc("确认收货失败");
	}

	/**
	 * 
	 * @date 2019年1月26日 下午5:05:13
	 * @author JaysonLee
	 * @Description: 评论后更新订单状态
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param orderGoodsId
	 * @return
	 *
	 */
	public boolean upDateOrderByGoodsOrderId(int orderGoodsId) {
		OrderGoods orderGoods = orderGoodsDao.getById(orderGoodsId, false);
		if (orderGoods == null) {
			return false;
		}
		HashMap<String, Object> param = new HashMap<>();
		param.put("id", orderGoods.getOrderId());
		param.put("state", OrderState.TO_BE_EVALUATED_STATE.getCode());// 确认收货待评价
		Order order = get(param, false);
		if (order == null) {
			return false;
		}
		order.setState(OrderState.COMPLETED_STATE.getCode());
		return update(order);
	}

	public Page<OrderGoods> pageSys(String keyword, String addressName, String startTime, String endTime, int states,
			int pageNumber, int pageSize, String address, String goodsName, int payType) {
		StringBuilder sql = new StringBuilder(" FROM shop_order_goods b ");
		sql.append(" LEFT JOIN shop_order a ON a.id = b.orderId ");
		sql.append(" LEFT JOIN shop_goods sg ON sg.id = a.goodsId");
		sql.append(" LEFT JOIN tb_account_user tau ON tau.accountId = sg.userId");
		sql.append(" LEFT JOIN tb_account ta ON ta.id = sg.userId");
		sql.append(SqlUtil._WHERE);
		SqlUtil.addLike(sql, " AND a.orderNo", "%", keyword, "%");
		SqlUtil.addLike(sql, " AND a.addressName", "%", addressName, "%");
		SqlUtil.addLike(sql, " AND a.address", "%", address, "%");
		SqlUtil.addLike(sql, " AND b.goodsName", "%", goodsName, "%");
		if (states != -1 && states != 4 && states != 5) {
			sql.append(" AND a.state = ").append(states);
		}
		SqlUtil.addSql(sql, " AND a.refundState = 1 ", states == 4);
		SqlUtil.addSql(sql, " AND a.refundState = 2 ", states == 5);
		SqlUtil.addWhere(sql, " AND a.payType =", payType, -1);
		if (JMToolString.areNotEmpty(startTime, endTime)) {
			String appendSql = JMToolSql.format(" AND a.createTime BETWEEN '%s' AND DATE_ADD('%s',INTERVAL 1 DAY)",
					startTime, endTime);
			sql.append(appendSql);
		}
		SqlUtil.changeWhere(sql);
		sql.append(" ORDER by a.id DESC");
		Page<OrderGoods> page = OrderGoods.dao.paginate(pageNumber, pageSize,
				"SELECT a.*,b.skuImg,b.price,b.num,b.goodsName,tau.nick,ta.mobile", sql.toString());
		return page;
	}

	/**
	 * 
	 * @date 2019年2月26日 下午4:16:43
	 * @author JaysonLee
	 * @Description: 发货
	 * @reqMethod post
	 * @paramter
	 * @pDescription
	 * @param orderId
	 * @param logisticsNo
	 * @return
	 *
	 */
	public JMResult deliveryOrder(int orderId, String logisticsNo) {
		HashMap<String, Object> param = new HashMap<>();
		param.put("id", orderId);
		param.put("state", 2);
		Order order = get(param, false);
		if (order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("该订单不存在，或者订单状态异常");
		}
		order.setRefundState(OrderState.NORMAL_REFUND_STATE.getCode());
		order.setExpressNo(logisticsNo);
		order.setState(DELIVERED);// 已发货
		order.setSendTime(new Date());
		update(order);

		// 定时十天收货
		ToolTimer.setTimer(order.getOrderNo(), orderId + "", 24 * 10 * 3600);
		return JMResult.create().code(JMResult.SUCCESS).desc("发货成功");
	}

	public JMResult updateOrderAddress(int addressId, String orderNo) {
		Order order = getByOrderNO(orderNo);
		if(order == null) {
			return JMResult.create().code(JMResult.FAIL).desc("该订单不存在，或者订单状态异常");
		}
		setOrderAddress(addressId, order);
		update(order);
		return JMResultUtil.success();
	}
	

	public Order selectByCanPayGoodsId(Integer goodsId, Integer orderId) {
		StringBuilder sql = new StringBuilder();
		sql.append("SELECT * FROM shop_order WHERE goodsId = ").append(goodsId)
			.append(" AND (state = 1 OR (state = 0 AND createTime >DATE_ADD(NOW(), INTERVAL -30 MINUTE))) ");
		SqlUtil.addWhere(sql, " AND id !=", orderId);
		return get(sql.toString(), false);
	}
	
	public JMResult selectOrderLogistics(String orderNo,Account account) throws Exception {
		Order order = getByOrderNo(orderNo);
		if(order == null) {
			return JMResultUtil.failDesc(JMMessage.ERROR);
		}
//		if(!order.getAccountId().equals(account.getId())) {
//			return JMResultUtil.failDesc(JMMessage.ERROR);
//		}
		KdniaoTrackQueryAPI kdniaoTrackQueryAPI = new KdniaoTrackQueryAPI();
		String shipperCode = kdniaoTrackQueryAPI.getShipperCode(order.getExpressNo());
		String orderTraces = kdniaoTrackQueryAPI.getOrderTraces(shipperCode, order.getExpressNo());
		JSONObject jsonObject = JSONObject.parseObject(orderTraces);
		JSONArray jsonArray = jsonObject.getJSONArray("Traces");
		List<JSONObject> list = jsonArray.toJavaList(JSONObject.class);
		//倒序
		Collections.sort(list, new Comparator<JSONObject>() {
			@Override
			public int compare(JSONObject o1, JSONObject o2) {
				Date a = o1.getDate("AcceptTime");
				Date b = o2.getDate("AcceptTime");
				if (a.compareTo(b)>0) {
					return -1;
				} else if(a.compareTo(b)==0) {
					return 0;
				} else
					return 1;
			}
		});
		jsonObject.put("Traces", list);
		return JMResultUtil.success(jsonObject);
	}

	public void cancelOtherByGoodsId(Integer goodsId) {
		Db.update("UPDATE shop_order SET `state` = 3 WHERE `state` = 0 AND goodsId = " + goodsId);
	}

	/**
	 * 获取商家出售商品后待入账金额
	 * @param accountId
	 * @return
	 */
	public BigDecimal cashPrice(int accountId) {
		return Db.queryBigDecimal("SELECT IFNULL(SUM(price), 0) " + 
					"FROM `shop_order` so " + 
					" INNER JOIN `shop_goods` sg ON sg.`id` = so.`goodsId` " + 
					"WHERE sg.`userId` = ? AND so.state IN (2, 7)",accountId);
	}

	/**
	 * 搜索我的直播间订单(分页)
	 * @param roomId
	 * @param state
	 * @param keyword
	 * @param minPrice
	 * @param maxPrice
	 * @param startTime
	 * @param endTime
	 * @param pageNumber
	 * @param pageSize
	 * @return 
	 */
	public Page<Order> pageMyRoomOrder(Integer roomId, int state, String keyword, String minPrice, String maxPrice,
			String startTime, String endTime, Integer pageNumber, Integer pageSize) {
		StringBuilder  fromSql = new  StringBuilder();
		appendOrderFromSql(fromSql, keyword, minPrice, maxPrice, startTime, endTime, state, AccountEnum.REGISTERTYPE_ANCHOR);
		fromSql.append(" AND so.orderType = 1 AND so.roomId =").append(roomId)
		.append(" ORDER BY so.id DESC");
		return dao.paginate(pageNumber, pageSize, false, "SELECT so.*,sg.name goodsName,sg.thumbnail,sg.price goodsPrice", fromSql.toString());
	}

	/**
	 * 搜索我的直播间订单(全部信息)
	 * @param roomId
	 * @param state
	 * @param keyword
	 * @param minPrice
	 * @param maxPrice
	 * @param startTime
	 * @param endTime
	 * @param pageNumber
	 * @param pageSize
	 * @return 
	 */
	public List<Order> myWebCastOrderNum(Integer roomId, Integer id, String keyword, String minPrice, String maxPrice,
			String startTime, String endTime, int state) {
		StringBuilder  fromSql = new  StringBuilder();
		fromSql.append("SELECT COUNT(so.id) num,so.state,so.refundState ");
		appendOrderFromSql(fromSql, keyword, minPrice, maxPrice, startTime, endTime, state, AccountEnum.REGISTERTYPE_ANCHOR);
		fromSql.append(" AND so.orderType = 1 AND so.roomId =").append(roomId);
		fromSql.append(" GROUP BY state,refundState");
		return dao.find(fromSql.toString());
	}
	/**
	 * 搜索我的商家端订单(分页)
	 * @param accountId
	 * @param state
	 * @param keyword
	 * @param minPrice
	 * @param maxPrice
	 * @param startTime
	 * @param endTime
	 * @param pageNumber
	 * @param pageSize
	 * @return 
	 */
	public Page<Order> pageMyShopOrder(Integer accountId, int state, String keyword, String minPrice, String maxPrice,
			String startTime, String endTime, Integer pageNumber, Integer pageSize) {
		StringBuilder  fromSql = new  StringBuilder();
		appendOrderFromSql(fromSql, keyword, minPrice, maxPrice, startTime, endTime, state, AccountEnum.REGISTERTYPE_SHOP);
		fromSql.append(" AND sg.userId =").append(accountId)
		.append(" ORDER BY so.id DESC");
		return dao.paginate(pageNumber, pageSize, false, "SELECT so.*,sg.name goodsName,sg.thumbnail,sg.price goodsPrice", fromSql.toString());
	}
	
	/**
	 * 搜索我的商家端订单(全部信息)
	 * @param accountId
	 * @param state
	 * @param keyword
	 * @param minPrice
	 * @param maxPrice
	 * @param startTime
	 * @param endTime
	 * @param pageNumber
	 * @param pageSize
	 * @return 
	 */
	public List<Order> myShopOrderNum(Integer accountId, Integer id, String keyword, String minPrice, String maxPrice,
			String startTime, String endTime, Integer state) {
		StringBuilder  fromSql = new  StringBuilder();
		fromSql.append("SELECT COUNT(so.id) num,so.state,so.refundState ");
		appendOrderFromSql(fromSql, keyword, minPrice, maxPrice, startTime, endTime, state, AccountEnum.REGISTERTYPE_SHOP);
		fromSql.append(" AND sg.userId =").append(accountId);
		fromSql.append(" GROUP BY state,refundState");
		return dao.find(fromSql.toString());
	}

	/**
	 * 搜索我的用户端订单(全部信息)
	 * @param accountId
	 * @param state
	 * @param keyword
	 * @param minPrice
	 * @param maxPrice
	 * @param startTime
	 * @param endTime
	 * @param pageNumber
	 * @param pageSize
	 * @return 
	 */
	public List<Order> myOrderNum(Integer accountId, Integer id, String keyword, String minPrice, String maxPrice,
			String startTime, String endTime, Integer state) {
		StringBuilder  fromSql = new  StringBuilder();
		fromSql.append("SELECT COUNT(so.id) num,so.state,so.refundState ");
		appendOrderFromSql(fromSql, keyword, minPrice, maxPrice, startTime, endTime, state, AccountEnum.REGISTERTYPE_USER);
		fromSql.append(" AND so.accountId =").append(accountId);
		fromSql.append(" GROUP BY state,refundState");
		return dao.find(fromSql.toString());
	}
	
	public void appendOrderFromSql(StringBuilder sql, String keyword, String minPrice,
			String maxPrice, String startTime, String endTime, Integer state, AccountEnum accountType) {
		sql.append("FROM shop_order so INNER JOIN shop_goods sg ON sg.id = so.goodsId")
		.append(" WHERE so.isDel = 0 AND sg.del = 0");
		SqlUtil.addSql(sql, " AND so.money >=", minPrice);
		SqlUtil.addSql(sql, " AND so.money <=", maxPrice);
		if(StrKit.notBlank(startTime)) {
			sql.append(" AND so.createTime <= '").append(startTime).append(" 23:59:59' ");
		}
		if(StrKit.notBlank(endTime)) {
			sql.append(" AND so.createTime >= '").append(endTime).append(" 00:00:00' ");
			
		}
		if(StrKit.notBlank(keyword)) {
			keyword = SqlUtil.replaceStr("%"+keyword+"%");
			sql.append(String.format(" AND ( so.orderNo LIKE %s OR sg.name LIKE %s)", keyword, keyword));
		}
		if(state == 0) {
			sql.append(" AND so.state IN (0,1)");
		}else if(state == 8) {
			if(AccountEnum.REGISTERTYPE_SHOP.equals(accountType)) {
				sql.append(" AND so.state IN (8,9)");
			}else {
				sql.append(" AND so.state = 8 ");
			}
		}else if(state != -1) {
			sql.append(" AND so.state =").append(state);
		}
	}
	/**
	 * 根据订单状态获取订单列表
	 * @param state
	 * @return 
	 */
	public List<Order> selectByState(String state,String day,String timeField) {
		return Order.dao.find(String.format("SELECT accountId,id FROM shop_order WHERE state = %s AND DATE_SUB(CURDATE(), INTERVAL %s DAY) > DATE(%s)",state,day,timeField));
	}

	/**
	 * 根据订单状态获取订单列表
	 * @param state
	 * @return 
	 */
	public void setByState(String state,String day,String timeField) {
		Db.update(String.format("UPDATE shop_order SET state = 6  WHERE state = %s AND DATE_SUB(CURDATE(), INTERVAL %s DAY) > DATE(%s)",state,day,timeField));
	}

}
