
package com.cn.jm.service;

import java.util.Date;

import com.cn._gen.model.Account;
import com.cn._gen.model.Suggest;
import com.cn.jm._dao.suggest.JMSuggestDao;
import com.jfinal.aop.Inject;
import com.jfinal.plugin.activerecord.Page;
/**
 * Generated by 小跑科技robot  .
 */
public class JMSuggestService extends BasicsService<Suggest> {
	
	@Inject
	JMSuggestDao suggestDao;
	
	public Page<Suggest> page(Integer pageNumber, Integer pageSize,Integer id,String keyword,String startTime,String endTime){
		return suggestDao.page(pageNumber,pageSize,id,keyword,startTime,endTime,false);
	}

	public boolean createSuggest(Account account, String content, String contact) {
		Suggest suggest = new Suggest();
		suggest.setAccountId(account.getId());
		suggest.setContent(content);
		suggest.setContact(contact);
		suggest.setCreateTime(new Date());
		return suggestDao.save(suggest);
	}
	
}