
package com.cn.jm._dao.follow;

import java.util.Date;

import com.cn._gen.model.Follow;
import com.cn.jm.core.JMMessage;
import com.cn.jm.core.utils.util.JMResult;
import com.cn.jm.util.JMResultUtil;
import com.jfinal.aop.Aop;
import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.tx.Tx;

/**
 * Generated by 广州小跑robot.
 */
public class JMFollowService {

	private JMFollowDao followDao = Aop.get(JMFollowDao.class);

	/**
	 * 
	 * @date 2018年12月8日 上午11:13:47
	 * @author lgk
	 * @Description: 添加收藏
	 *
	 */
	@Before(Tx.class)
	public void insertFollow(Follow follow) {
//		followDao.check(follow.getIds(), follow.getAccountId(), type)
		follow.setCreateTime(new Date());
		follow.save();
	}

	/**
	 * 
	 * @date 2018年12月8日 上午11:25:55
	 * @author lgk
	 * @Description: 取消收藏
	 * @param pojo
	 * @return
	 *
	 */
	@Before(Tx.class)
	public JMResult cancelFollowRes(Follow pojo) {
		Follow follow = followDao.selectFollowRes(pojo);
		if (follow == null)
			return JMResultUtil.fail(JMMessage.RECORD_NOT_EXIST);

		if (!follow.getAccountId().equals(pojo.getAccountId()))
			return JMResultUtil.fail(JMMessage.PRIVILEGE_NOT_ENOUGH);

		follow.delete();
		return JMResultUtil.success(JMMessage.SUCCESS);
	}

}
