
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountSession<M extends BaseAccountSession<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setSessionId(java.lang.String sessionId) {
		set("sessionId", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("sessionId");
	}

	public void setOvertime(java.lang.Long overtime) {
		set("overtime", overtime);
	}

	public java.lang.Long getOvertime() {
		return get("overtime");
	}

	public void setSessionSalt(java.lang.String sessionSalt) {
		set("sessionSalt", sessionSalt);
	}

	public java.lang.String getSessionSalt() {
		return get("sessionSalt");
	}



}