
package com.cn._gen.model;

import com.cn._gen.model.base.BaseOrder;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	
	public static final Order dao = new Order().dao();
	
}