
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRefundOrder;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RefundOrder extends BaseRefundOrder<RefundOrder> {
	
	public static final RefundOrder dao = new RefundOrder().dao();
	
}