
package com.cn.jm._dao.marketing;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cn._gen.dao.MarketingGoodsDao;
import com.cn._gen.model.Goods;
import com.cn._gen.model.MarketingGoods;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;





/**
 * Generated by 广州小跑robot.
 */
public class JMMarketingGoodsDao extends MarketingGoodsDao{
	
	public boolean add(Integer goodsIds[],int marketId) {
		Db.delete("delete from shop_marketing_goods where marketId = ?",marketId);
		if(goodsIds != null) {
			List<MarketingGoods> list = new ArrayList<MarketingGoods>();
			for(int goodsId : goodsIds) {
				MarketingGoods marketingGoods = new MarketingGoods();
				marketingGoods.setGoodsId(goodsId);
				marketingGoods.setMarketId(marketId);
				marketingGoods.setCreateTime(new Date());
				list.add(marketingGoods);
			}
			int result[] = Db.batchSave(list, list.size() > 1000 ? 1000 : list.size());
			return result.length == list.size();
		}
		return true ;
	}
	
	
	public boolean removeGoods(Integer marketingGoodsIds[]) {
		String ids = "";
		for(int id : marketingGoodsIds) {
			ids += id + ",";
		}
		if(ids.endsWith(",")) {
			ids = ids.substring(0,ids.length() - 1);
		}
		int result = Db.update("delete from shop_marketing_goods where id in ("+ids+")");
		return result == marketingGoodsIds.length ;
	}
	
	/**
	 * 
	 * @date 2019年3月13日 上午9:16:02
	 * @author JaysonLee
	 * @Description: 批量上下架
	 * @reqMethod post
	 * @paramter
	 * @pDescription	
	 * @param marketingGoodsIds
	 * @return
	 *
	 */
	public boolean fz(Integer marketingGoodsIds[],int fz) {
		String ids = "";
		for(int id : marketingGoodsIds) {
			ids += id + ",";
		}
		if(ids.endsWith(",")) {
			ids = ids.substring(0,ids.length() - 1);
		}
		int result = Db.update("update shop_marketing_goods set fz = ? where id in ("+ids+")",fz);
		return result == marketingGoodsIds.length ;
	}
	
	
	public List<Goods> listByMarketId(int marketId,String keyword){
		List<Goods> list = Goods.dao.find("select a.id,a.name from shop_goods a where a.id in (select goodsId from shop_marketing_goods where marketId = ?) and a.name like '%"+keyword+"%'",marketId);
		for(Goods goods : list) {
			goods.put("goodsId",String.valueOf(goods.getId()));
		}
		return list ;
	}
	
	
	public Page<Goods> pageGoodsByMarketId(int marketId,String keyword,int pageSize,int pageNumber){
		Page<Goods> page = Goods.dao.paginate(pageNumber, pageSize, "select a.*", 
				" from shop_goods a where a.id in (select goodsId from shop_marketing_goods where marketId = ?) and a.name like '%"+keyword+"%' ",marketId);
		return page ;
	}
	
}
