
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRoomAccount;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RoomAccount extends BaseRoomAccount<RoomAccount> {
	
	public static final RoomAccount dao = new RoomAccount().dao();
	
}