
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseRoomManagement<M extends BaseRoomManagement<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setManageAccountId(java.lang.Integer manageAccountId) {
		set("manageAccountId", manageAccountId);
	}

	public java.lang.Integer getManageAccountId() {
		return get("manageAccountId");
	}

	public void setMerchantAccountId(java.lang.Integer merchantAccountId) {
		set("merchantAccountId", merchantAccountId);
	}

	public java.lang.Integer getMerchantAccountId() {
		return get("merchantAccountId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}



}