
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRoomManagement;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class RoomManagement extends BaseRoomManagement<RoomManagement> {
	
	public static final RoomManagement dao = new RoomManagement().dao();
	
}