
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseSpecModels<M extends BaseSpecModels<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSpecId(java.lang.Integer specId) {
		set("specId", specId);
	}

	public java.lang.Integer getSpecId() {
		return get("specId");
	}

	public void setModelsId(java.lang.Integer modelsId) {
		set("modelsId", modelsId);
	}

	public java.lang.Integer getModelsId() {
		return get("modelsId");
	}



}