
package com.cn.jm._dao.marketing;

import java.util.List;

import com.cn._gen.dao.MarketingDao;
import com.cn._gen.model.Marketing;


/**
 * Generated by 广州小跑robot.
 */
public class JMMarketingDao extends MarketingDao{
	
	public List<Marketing> listAll(){
		List<Marketing> list = Marketing.dao.find("select * from shop_marketing order by sort DESC");
		return list ;
	}
	
}
