
package com.cn.jm.controller.shop.system;

import java.util.Date;
import java.util.HashMap;

import com.cn._gen.model.Keyword;
import com.cn.jm._dao.keyword.JMKeywordDao;
import com.cn.jm.core.JMConsts;
import com.cn.jm.core.tool.JMToolString;
import com.cn.jm.core.utils.util.JMResult;
import com.cn.jm.core.web.controller.JMBaseSystemController;
import com.cn.jm.core.web.dao.JMBaseDao;
import com.cn.jm.interceptor.SystemLoginInterceptor;
import com.cn.jm.web.core.router.JMRouterMapping;
import com.jfinal.aop.Before;
import com.jfinal.aop.Inject;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by 广州小跑robot.
 */

@JMRouterMapping(url = SystemKeywordController.url)
@Before(value={SystemLoginInterceptor.class})
public class SystemKeywordController extends JMBaseSystemController {
	
	public static final String path = JMConsts.base_view_url+"/system/base/keyword";
	public static final String url ="/system/keyword";
	
	@Inject
	public JMKeywordDao keywordDao;

	public void index(){
		page();
	}

	public void page(){
		String keyword = getPara("keyword","");
		Integer id = getParaToInt("id");
		
		String startTime = getPara("startTime","");
		String endTime = getPara("endTime","");
		
		Integer pageNumber = getParaToInt(0, 1);
		Integer pageSize = JMConsts.pageSize;
		
		HashMap<String, Object> andpm = new HashMap<String, Object>();
		HashMap<String, Object> likepm = new HashMap<String, Object>();
		HashMap<String, Object> orpm = new HashMap<String, Object>();
		
		if (id == null) {
			if (JMToolString.isNotEmpty(keyword)) {
				likepm.put("name", keyword);
			}
		}else {
			andpm.put("id", id);
		}
		Page<Keyword> page = null;
		
		if (JMToolString.isNotEmpty(startTime) && JMToolString.isNotEmpty(endTime)) {
			page = keywordDao.page(pageNumber, pageSize, "", andpm, orpm, likepm, startTime,endTime,"id", JMBaseDao.DESC, true);
		}else {
			page = keywordDao.page(pageNumber, pageSize, "", andpm, orpm, likepm, "id", JMBaseDao.DESC, true);
		}
		
		setAttr("id", id);
		setAttr("keyword", keyword);
		setAttr("startTime", startTime);
		setAttr("endTime", endTime);
		setAttr("page", page);
		
		jump();
		render(path+"/page.html");
	}
	
	public void add(){
		Keyword keyword = new Keyword();
		setAttr("action", JMConsts.ACTION_ADD);
		setAttr("keyword", keyword);
		render(path+"/add.html");
	}

	public void save(){
		Keyword keyword = getModel(Keyword.class);
		keyword.setCreateTime(new Date());
		boolean result = keywordDao.save(keyword);
		if(result){
			JMResult.success(this, "添加成功");
		}else{
			JMResult.fail(this, "添加失败");
		}
	}
	
	public void edit(){
		int id = getParaToInt("id");
		Keyword keyword = keywordDao.getById(id);
		setAttr("keyword",keyword);
		render(path+"/edit.html");
	}

	public void update(){
		Keyword keyword = getModel(Keyword.class);
		boolean result = keywordDao.update(keyword);
		if(result){
			JMResult.success(this, "编辑成功");
		}else{
			JMResult.fail(this, "编辑失败");
		}
	}
	
	public void delete(){
		int id = getParaToInt("id");
		
		if (keywordDao.deleteById(id)) {
			JMResult.success(this, "删除成功");
		}else {
			JMResult.fail(this, "删除失败");
		}
	}
	
	public void dels(){
		Integer[] ids = getParaValuesToInt("ids");
		if(ids != null){
			boolean result = keywordDao.deleteByIds(ids);
			if (result) {
				JMResult.success(this, "删除成功");
			}else {
				JMResult.fail(this, "删除失败");
			}
		}else {
			JMResult.fail(this, "请选择需要删除的数据");
		}
	}

}