
package com.cn._gen.model;

import com.cn._gen.model.base.BaseCash;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Cash extends BaseCash<Cash> {
	
	public static final Cash dao = new Cash().dao();
	
}