
package com.cn._gen.model;

import com.cn._gen.model.base.BaseReport;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Report extends BaseReport<Report> {
	
	public static final Report dao = new Report().dao();
	
}