
package com.cn._gen.model;

import com.cn._gen.model.base.BaseArea;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	
	public static final Area dao = new Area().dao();
	
}