
package com.cn._gen.model;

import com.cn._gen.model.base.BaseRoom;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Room extends BaseRoom<Room> {
	
	public static final Room dao = new Room().dao();
	
}