
package com.cn.jm._dao.search;

import java.util.HashMap;
import java.util.List;

import com.cn._gen.dao.SearchHistoryDao;
import com.cn._gen.model.SearchHistory;


/**
 * Generated by 广州小跑robot.
 */
public class JMSearchHistoryDao extends SearchHistoryDao{
	
	public void add(Integer userId,String message,Integer shopId){
		SearchHistory searchHistory = new SearchHistory();
		if(userId != null)
			searchHistory.setAccountId(userId);
		searchHistory.setMessage(message);
		if(shopId != null)
			searchHistory.setShopId(shopId);
		save(searchHistory);
	}

	/**
	 * 
	 * @date 2019年1月25日 下午2:11:39
	 * @author JaysonLee
	 * @Description: 热门搜索记录
	 * @reqMethod post
	 * @paramter
	 * @pDescription	
	 * @return
	 *
	 */
	public List<SearchHistory> hotList(){
		HashMap<String, Object> param = new HashMap<>();
		param.put("accountId",-1);//热门
		return list("",param,"sort","DESC",false);
	}
	
}
