
package com.cn._gen.model;

import com.cn._gen.model.base.BaseBroadcastRequest;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class BroadcastRequest extends BaseBroadcastRequest<BroadcastRequest> {
	
	public static final BroadcastRequest dao = new BroadcastRequest().dao();
	
}