
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseSpecGroup<M extends BaseSpecGroup<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setSpecId(java.lang.Integer specId) {
		set("specId", specId);
	}

	public java.lang.Integer getSpecId() {
		return get("specId");
	}

	public void setSpecAttrId(java.lang.Integer specAttrId) {
		set("specAttrId", specAttrId);
	}

	public java.lang.Integer getSpecAttrId() {
		return get("specAttrId");
	}



}