
package com.cn._gen.model;

import com.cn._gen.model.base.BaseMenu;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	
	public static final Menu dao = new Menu().dao();
	
}