
package com.cn.jm._dao.room;

import com.cn._gen.dao.RoomManagementDao;
import com.cn._gen.model.RoomManagement;
import com.cn.jm.core.constants.JMConstants;
import com.cn.jm.util.SqlUtil;
import com.cn.jm.util.sqltool.JMCommonDao;
import com.cn.jm.util.sqltool.Query;
import com.jfinal.kit.HashKit;
import com.jfinal.plugin.activerecord.Page;


/**
 * Generated by 广州小跑robot.
 */
public class JMRoomManagementDao extends RoomManagementDao{
	
	private JMCommonDao commonDao = JMCommonDao.jmd;
	
	public Page<RoomManagement> page(Integer pageNumber, Integer pageSize,Integer id,String keyword,String startTime,String endTime,boolean isCache){
		StringBuilder selectSql = new StringBuilder("SELECT id ");
		StringBuilder fromSql = new StringBuilder(" FROM ");
		fromSql.append(tableName);
		fromSql.append(" :WHERE ");
		SqlUtil.addWhere(fromSql," AND id = ",id);
		SqlUtil.addLike(fromSql," AND name","%",keyword,"%");
		SqlUtil.addBetweenTime(fromSql, startTime, endTime, " AND createTime");
		String strFromSql = fromSql.toString();
		String strSelectSql = selectSql.toString();
		return isCache?dao.paginateByCache(cacheName,HashKit.md5(selectSql.append(strFromSql).toString()), pageNumber, pageSize,false,strSelectSql, strFromSql)
			:dao.paginate(pageNumber, pageSize, false, strSelectSql,strFromSql);
	}
	
	
	public boolean check(Integer merchantAccountId) {
		Query query = new Query();
		query.put("and merchantAccountId = ", merchantAccountId);
		query.put("and state = ", JMConstants.NORMAL);
		return commonDao.selectOne(RoomManagement.class, query)!=null;
	}
	
	
	public boolean checkIsBind(Integer anchorAccountId) {
		Query query = new Query();
		query.put("and rm.anchorAccountId =", anchorAccountId);
		query.put("and rm.state = ", JMConstants.NORMAL);
		query.put("and me.state = ", JMConstants.NORMAL);
		String select = "select *";
		String inner = "rm inner join webcast_room_merchant me on rm.merchantAccountId = me.merchantAccountId";
		return commonDao.selectOne(RoomManagement.class, query, select, inner)!=null;
	}
	
	public RoomManagement selectRoomManagement(Integer anchorAccountId) {
		Query query = new Query();
		query.put("and anchorAccountId =", anchorAccountId);
		query.put("and state = ", JMConstants.NORMAL);
		String select = "select *";
		return commonDao.selectOne(RoomManagement.class, query, select);
	}
	
	
}
