
package com.cn._gen.model;

import com.cn._gen.model.base.BaseMarketing;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Marketing extends BaseMarketing<Marketing> {
	
	public static final Marketing dao = new Marketing().dao();
	
}