
package com.cn._gen.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by 小跑科技robot.
 */
@SuppressWarnings("serial")
public abstract class BaseWebcastRoomRecord<M extends BaseWebcastRoomRecord<M>> extends Model<M> implements IBean {

		public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("roomId");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setPeakNumber(java.lang.Integer peakNumber) {
		set("peakNumber", peakNumber);
	}

	public java.lang.Integer getPeakNumber() {
		return get("peakNumber");
	}

	public void setPlayUrl(java.lang.String playUrl) {
		set("playUrl", playUrl);
	}

	public java.lang.String getPlayUrl() {
		return get("playUrl");
	}

	public void setPushUrl(java.lang.String pushUrl) {
		set("pushUrl", pushUrl);
	}

	public java.lang.String getPushUrl() {
		return get("pushUrl");
	}

	public void setWatchNumber(java.lang.Integer watchNumber) {
		set("watchNumber", watchNumber);
	}

	public java.lang.Integer getWatchNumber() {
		return get("watchNumber");
	}



}