
package com.cn._gen.model;

import com.cn._gen.model.base.BaseConfigure;

/**
 * Generated by 广州小跑robot.
 */
@SuppressWarnings("serial")
public class Configure extends BaseConfigure<Configure> {
	
	public static final Configure dao = new Configure().dao();
	
}