
package com.cn.jm.service;

import com.cn.jm._dao.img.ImgEnum;
import com.cn.jm._dao.img.JMImgDao;
import com.cn.jm.information.BasicsInformation;
import com.jfinal.aop.Inject;
import com.jfinal.plugin.activerecord.Page;

import cn.hutool.core.date.DateUtil;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cn._gen.model.Img;
/**
 * Generated by 小跑科技robot  .
 */
public class JMImgService extends BasicsService<Img> {
	
	@Inject
	JMImgDao imgDao;
	
	public Page<Img> page(Integer pageNumber, Integer pageSize,Integer id,String keyword,String startTime,String endTime){
		return imgDao.page(pageNumber,pageSize,id,keyword,startTime,endTime,false);
	}

	/**
	 * 添加商品的关联图片
	 * @param goodsId
	 * @param detailImageList
	 * @param goodsImageList
	 * @return 
	 */
	public boolean inserImages(Integer goodsId, ArrayList<String> detailImageList, ArrayList<String> goodsImageList) {
		if((detailImageList != null && goodsImageList != null) && (detailImageList.size() > 0 || goodsImageList.size() > 0)) {
			try {
				imgDao.inserGoodsImages(goodsId, detailImageList, goodsImageList, DateUtil.format(new Date(), BasicsInformation.DATE_FORMAT));
				return true;
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return false;
	}

	public List<Img> selectByTypeAndIds(Integer ids, ImgEnum imgType) {
		return imgDao.selectByTypeAndIds(ids, imgType);
	}
	
	public Integer countImageNum(Integer ids, ImgEnum imgType) {
		return imgDao.countImageNum(ids, imgType);
	}
	
	/**
	 * 根据条件删除商品详情图和主图
	 * @param detailNotInIds
	 * @param goodsNotInIds
	 * @param goodsId
	 */
	public void deleteGoodsImage(String[] detailNotInIds, String[] goodsNotInIds, Integer goodsId) {
		imgDao.deleteNotInByIdsAndType(goodsId, ImgEnum.GOODS_DETAILS_TYPE, detailNotInIds);
		imgDao.deleteNotInByIdsAndType(goodsId, ImgEnum.GOODS_OWNER_TYPE, goodsNotInIds);
	}
	
	public int deleteResaleGoodsImage(int resaleGoodsId, String[] notInIds) {
		return imgDao.deleteNotInByIdsAndType(resaleGoodsId, ImgEnum.RESALE_GOODS__DETAILS_TYPE, notInIds);
	}
}

